- generic [active] [ref=e1]:
  - banner [ref=e2]:
    - generic [ref=e3]:
      - generic [ref=e4]: MC
      - generic [ref=e5]: CigarDomTabaka
      - generic [ref=e6]: · 品牌目录
    - navigation [ref=e7]:
      - link "品牌" [ref=e8] [cursor=pointer]:
        - /url: /
        - img [ref=e9]
        - text: 品牌
    - link "登录" [ref=e12] [cursor=pointer]:
      - /url: /login/
  - main [ref=e13]:
    - generic [ref=e14]:
      - generic [ref=e15]:
        - heading "古巴雪茄目录" [level=1] [ref=e16]
        - generic [ref=e17]: 52 个品牌 · 完整收录
      - generic [ref=e19]:
        - text: ⌕
        - textbox "搜索品牌名称..." [ref=e20]
    - main [ref=e21]:
      - generic [ref=e22]:
        - generic [ref=e23]:
          - heading "🌍 全球品牌 (6)" [level=2] [ref=e24]
          - text: 6 个品牌
        - generic [ref=e25]:
          - link "高希霸 高希霸 89 款雪茄 古巴 全球" [ref=e26] [cursor=pointer]:
            - /url: /brand/cohiba/
            - img "高希霸" [ref=e28]
            - generic [ref=e29]: 高希霸
            - generic [ref=e30]: 89 款雪茄
            - generic [ref=e31]: 古巴 全球
          - link "乌普曼 乌普曼 70 款雪茄 古巴 全球" [ref=e32] [cursor=pointer]:
            - /url: /brand/h-upmann/
            - img "乌普曼" [ref=e34]
            - generic [ref=e35]: 乌普曼
            - generic [ref=e36]: 70 款雪茄
            - generic [ref=e37]: 古巴 全球
          - link "好友 好友 69 款雪茄 古巴 全球" [ref=e38] [cursor=pointer]:
            - /url: /brand/hoyo-de-monterrey/
            - img "好友" [ref=e40]
            - generic [ref=e41]: 好友
            - generic [ref=e42]: 69 款雪茄
            - generic [ref=e43]: 古巴 全球
          - link "蒙特 蒙特 80 款雪茄 古巴 全球" [ref=e44] [cursor=pointer]:
            - /url: /brand/montecristo/
            - img "蒙特" [ref=e46]
            - generic [ref=e47]: 蒙特
            - generic [ref=e48]: 80 款雪茄
            - generic [ref=e49]: 古巴 全球
          - link "帕特加斯 帕特加斯 123 款雪茄 古巴 全球" [ref=e50] [cursor=pointer]:
            - /url: /brand/partagas/
            - img "帕特加斯" [ref=e52]
            - generic [ref=e53]: 帕特加斯
            - generic [ref=e54]: 123 款雪茄
            - generic [ref=e55]: 古巴 全球
          - link "罗密欧与朱丽叶 罗密欧与朱丽叶 100 款雪茄 古巴 全球" [ref=e56] [cursor=pointer]:
            - /url: /brand/romeo-y-julieta/
            - img "罗密欧与朱丽叶" [ref=e58]
            - generic [ref=e59]: 罗密欧与朱丽叶
            - generic [ref=e60]: 100 款雪茄
            - generic [ref=e61]: 古巴 全球
      - separator [ref=e62]
      - generic [ref=e63]:
        - generic [ref=e64]:
          - heading "💎 价值品牌 (5)" [level=2] [ref=e65]
          - text: 5 个品牌
        - generic [ref=e66]:
          - link "玻利瓦 玻利瓦 83 款雪茄 古巴 价值" [ref=e67] [cursor=pointer]:
            - /url: /brand/bolivar/
            - img "玻利瓦" [ref=e69]
            - generic [ref=e70]: 玻利瓦
            - generic [ref=e71]: 83 款雪茄
            - generic [ref=e72]: 古巴 价值
          - link "潘趣 潘趣 74 款雪茄 古巴 价值" [ref=e73] [cursor=pointer]:
            - /url: /brand/punch/
            - img "潘趣" [ref=e75]
            - generic [ref=e76]: 潘趣
            - generic [ref=e77]: 74 款雪茄
            - generic [ref=e78]: 古巴 价值
          - link "希多尔赛 希多尔赛 21 款雪茄 古巴 价值" [ref=e79] [cursor=pointer]:
            - /url: /brand/quai-dorsay/
            - img "希多尔赛" [ref=e81]
            - generic [ref=e82]: 希多尔赛
            - generic [ref=e83]: 21 款雪茄
            - generic [ref=e84]: 古巴 价值
          - link "雷蒙阿隆尼 雷蒙阿隆尼 80 款雪茄 古巴 价值" [ref=e85] [cursor=pointer]:
            - /url: /brand/ramon-allones/
            - img "雷蒙阿隆尼" [ref=e87]
            - generic [ref=e88]: 雷蒙阿隆尼
            - generic [ref=e89]: 80 款雪茄
            - generic [ref=e90]: 古巴 价值
          - link "千里达 千里达 30 款雪茄 古巴 价值" [ref=e91] [cursor=pointer]:
            - /url: /brand/trinidad/
            - img "千里达" [ref=e93]
            - generic [ref=e94]: 千里达
            - generic [ref=e95]: 30 款雪茄
            - generic [ref=e96]: 古巴 价值
      - separator [ref=e97]
      - generic [ref=e98]:
        - generic [ref=e99]:
          - heading "📦 走量品牌 (3)" [level=2] [ref=e100]
          - text: 3 个品牌
        - generic [ref=e101]:
          - link "荷西比雅达 荷西比雅达 11 款雪茄 古巴" [ref=e102] [cursor=pointer]:
            - /url: /brand/jose-l-piedra/
            - img "荷西比雅达" [ref=e104]
            - generic [ref=e105]: 荷西比雅达
            - generic [ref=e106]: 11 款雪茄
            - generic [ref=e107]: 古巴
          - link "金特罗 金特罗 16 款雪茄 古巴" [ref=e108] [cursor=pointer]:
            - /url: /brand/quintero/
            - img "金特罗" [ref=e110]
            - generic [ref=e111]: 金特罗
            - generic [ref=e112]: 16 款雪茄
            - generic [ref=e113]: 古巴
          - link "威古洛 威古洛 11 款雪茄 古巴" [ref=e114] [cursor=pointer]:
            - /url: /brand/vegueros/
            - img "威古洛" [ref=e116]
            - generic [ref=e117]: 威古洛
            - generic [ref=e118]: 11 款雪茄
            - generic [ref=e119]: 古巴
      - separator [ref=e120]
      - generic [ref=e121]:
        - generic [ref=e122]:
          - heading "📋 其他品牌 (13)" [level=2] [ref=e123]
          - text: 13 个品牌
        - generic [ref=e124]:
          - link "库阿巴 库阿巴 17 款雪茄 古巴" [ref=e125] [cursor=pointer]:
            - /url: /brand/cuaba/
            - img "库阿巴" [ref=e127]
            - generic [ref=e128]: 库阿巴
            - generic [ref=e129]: 17 款雪茄
            - generic [ref=e130]: 古巴
          - link "外交官 外交官 25 款雪茄 古巴" [ref=e131] [cursor=pointer]:
            - /url: /brand/diplomaticos/
            - img "外交官" [ref=e133]
            - generic [ref=e134]: 外交官
            - generic [ref=e135]: 25 款雪茄
            - generic [ref=e136]: 古巴
          - link "世界之王 世界之王 42 款雪茄 古巴" [ref=e137] [cursor=pointer]:
            - /url: /brand/el-rey-del-mundo/
            - img "世界之王" [ref=e139]
            - generic [ref=e140]: 世界之王
            - generic [ref=e141]: 42 款雪茄
            - generic [ref=e142]: 古巴
          - link "科塞卡 科塞卡 9 款雪茄 古巴" [ref=e143] [cursor=pointer]:
            - /url: /brand/fonseca/
            - img "科塞卡" [ref=e145]
            - generic [ref=e146]: 科塞卡
            - generic [ref=e147]: 9 款雪茄
            - generic [ref=e148]: 古巴
          - link "胡安佩洛斯 胡安佩洛斯 42 款雪茄 古巴" [ref=e149] [cursor=pointer]:
            - /url: /brand/juan-lopez/
            - img "胡安佩洛斯" [ref=e151]
            - generic [ref=e152]: 胡安佩洛斯
            - generic [ref=e153]: 42 款雪茄
            - generic [ref=e154]: 古巴
          - link "卡诺之花 卡诺之花 20 款雪茄 古巴" [ref=e155] [cursor=pointer]:
            - /url: /brand/la-flor-de-cano/
            - img "卡诺之花" [ref=e157]
            - generic [ref=e158]: 卡诺之花
            - generic [ref=e159]: 20 款雪茄
            - generic [ref=e160]: 古巴
          - link "古巴荣耀 古巴荣耀 36 款雪茄 古巴" [ref=e161] [cursor=pointer]:
            - /url: /brand/la-gloria-cubana/
            - img "古巴荣耀" [ref=e163]
            - generic [ref=e164]: 古巴荣耀
            - generic [ref=e165]: 36 款雪茄
            - generic [ref=e166]: 古巴
          - link "波尔拉腊尼加 波尔拉腊尼加 48 款雪茄 古巴" [ref=e167] [cursor=pointer]:
            - /url: /brand/por-larranaga/
            - img "波尔拉腊尼加" [ref=e169]
            - generic [ref=e170]: 波尔拉腊尼加
            - generic [ref=e171]: 48 款雪茄
            - generic [ref=e172]: 古巴
          - link "拉斐尔 拉斐尔 18 款雪茄 古巴" [ref=e173] [cursor=pointer]:
            - /url: /brand/rafael-gonzalez/
            - img "拉斐尔" [ref=e175]
            - generic [ref=e176]: 拉斐尔
            - generic [ref=e177]: 18 款雪茄
            - generic [ref=e178]: 古巴
          - link "圣路易斯雷伊 圣路易斯雷伊 23 款雪茄 古巴" [ref=e179] [cursor=pointer]:
            - /url: /brand/saint-luis-rey/
            - img "圣路易斯雷伊" [ref=e181]
            - generic [ref=e182]: 圣路易斯雷伊
            - generic [ref=e183]: 23 款雪茄
            - generic [ref=e184]: 古巴
          - link "圣克里斯多 圣克里斯多 古巴" [ref=e185] [cursor=pointer]:
            - /url: /brand/san-cristobal-de-la-habana/
            - img "圣克里斯多" [ref=e187]
            - generic [ref=e188]: 圣克里斯多
            - generic [ref=e189]: 古巴
          - link "桑丘潘萨 桑丘潘萨 22 款雪茄 古巴" [ref=e190] [cursor=pointer]:
            - /url: /brand/sancho-panza/
            - img "桑丘潘萨" [ref=e192]
            - generic [ref=e193]: 桑丘潘萨
            - generic [ref=e194]: 22 款雪茄
            - generic [ref=e195]: 古巴
          - link "瓦格斯陆班纳 瓦格斯陆班纳 17 款雪茄 古巴" [ref=e196] [cursor=pointer]:
            - /url: /brand/vegas-robaina/
            - img "瓦格斯陆班纳" [ref=e198]
            - generic [ref=e199]: 瓦格斯陆班纳
            - generic [ref=e200]: 17 款雪茄
            - generic [ref=e201]: 古巴
      - separator [ref=e202]
      - generic [ref=e203]:
        - generic [ref=e204]:
          - heading "🏭 ICT 机制 (4)" [level=2] [ref=e205]
          - text: 4 个品牌
        - generic [ref=e206]:
          - link "贝琳达 贝琳达 古巴" [ref=e207] [cursor=pointer]:
            - /url: /brand/belinda/
            - img "贝琳达" [ref=e209]
            - generic [ref=e210]: 贝琳达
            - generic [ref=e211]: 古巴
          - link "关达拉美拉 关达拉美拉 10 款雪茄 古巴" [ref=e212] [cursor=pointer]:
            - /url: /brand/guantanamera/
            - img "关达拉美拉" [ref=e214]
            - generic [ref=e215]: 关达拉美拉
            - generic [ref=e216]: 10 款雪茄
            - generic [ref=e217]: 古巴
          - link "小雪茄 小雪茄 古巴" [ref=e218] [cursor=pointer]:
            - /url: /brand/small-cigars/
            - img "小雪茄" [ref=e220]
            - generic [ref=e221]: 小雪茄
            - generic [ref=e222]: 古巴
          - link "特洛伊 特洛伊 古巴" [ref=e223] [cursor=pointer]:
            - /url: /brand/troya/
            - img "特洛伊" [ref=e225]
            - generic [ref=e226]: 特洛伊
            - generic [ref=e227]: 古巴
      - separator [ref=e228]
      - generic [ref=e229]:
        - generic [ref=e230]:
          - heading "⭐ 特殊品牌 (4)" [level=2] [ref=e231]
          - text: 4 个品牌
        - generic [ref=e232]:
          - link "古巴雪茄 古巴雪茄 古巴" [ref=e233] [cursor=pointer]:
            - /url: /brand/cubatabaco/
            - img "古巴雪茄" [ref=e235]
            - generic [ref=e236]: 古巴雪茄
            - generic [ref=e237]: 古巴
          - link "艾蒙度但丁 艾蒙度但丁 古巴" [ref=e238] [cursor=pointer]:
            - /url: /brand/edmundo-dantes/
            - img "艾蒙度但丁" [ref=e240]
            - generic [ref=e241]: 艾蒙度但丁
            - generic [ref=e242]: 古巴
          - link "哈伯纳斯 哈伯纳斯 古巴" [ref=e243] [cursor=pointer]:
            - /url: /brand/habanos/
            - img "哈伯纳斯" [ref=e245]
            - generic [ref=e246]: 哈伯纳斯
            - generic [ref=e247]: 古巴
          - link "精选品牌系列 精选品牌系列 古巴" [ref=e248] [cursor=pointer]:
            - /url: /brand/multi-brand-releases/
            - img "精选品牌系列" [ref=e250]
            - generic [ref=e251]: 精选品牌系列
            - generic [ref=e252]: 古巴
      - separator [ref=e253]
      - generic [ref=e254]:
        - generic [ref=e255]:
          - heading "🪦 已停产品牌 (17)" [level=2] [ref=e256]
          - text: 17 个品牌
        - generic [ref=e257]:
          - link "卡班纳 卡班纳 古巴 停产" [ref=e258] [cursor=pointer]:
            - /url: /brand/cabanas/
            - img "卡班纳" [ref=e260]
            - generic [ref=e261]: 卡班纳
            - generic [ref=e262]: 古巴 停产
          - link "凯尼 凯尼 古巴 停产" [ref=e263] [cursor=pointer]:
            - /url: /brand/caney/
            - img "凯尼" [ref=e265]
            - generic [ref=e266]: 凯尼
            - generic [ref=e267]: 古巴 停产
          - link "西福恩特斯 西福恩特斯 古巴 停产" [ref=e268] [cursor=pointer]:
            - /url: /brand/cifuentes/
            - img "西福恩特斯" [ref=e270]
            - generic [ref=e271]: 西福恩特斯
            - generic [ref=e272]: 古巴 停产
          - link "大卫杜夫 大卫杜夫 停产" [ref=e273] [cursor=pointer]:
            - /url: /brand/davidoff/
            - img "大卫杜夫" [ref=e275]
            - generic [ref=e276]: 大卫杜夫
            - generic [ref=e277]: 停产
          - link "唐、阿尔佛 唐、阿尔佛 古巴 停产" [ref=e278] [cursor=pointer]:
            - /url: /brand/don-alfredo/
            - img "唐、阿尔佛" [ref=e280]
            - generic [ref=e281]: 唐、阿尔佛
            - generic [ref=e282]: 古巴 停产
          - link "唐、坎迪多 唐、坎迪多 古巴 停产" [ref=e283] [cursor=pointer]:
            - /url: /brand/don-candido/
            - img "唐、坎迪多" [ref=e285]
            - generic [ref=e286]: 唐、坎迪多
            - generic [ref=e287]: 古巴 停产
          - link "登喜路 登喜路 停产" [ref=e288] [cursor=pointer]:
            - /url: /brand/dunhill/
            - img "登喜路" [ref=e290]
            - generic [ref=e291]: 登喜路
            - generic [ref=e292]: 停产
          - link "繁花 繁花 古巴 停产" [ref=e293] [cursor=pointer]:
            - /url: /brand/flor-del-punto/
            - img "繁花" [ref=e295]
            - generic [ref=e296]: 繁花
            - generic [ref=e297]: 古巴 停产
          - link "基斯伯 基斯伯 古巴 停产" [ref=e298] [cursor=pointer]:
            - /url: /brand/gispert/
            - img "基斯伯" [ref=e300]
            - generic [ref=e301]: 基斯伯
            - generic [ref=e302]: 古巴 停产
          - link "J.J·福克斯 专享 J.J·福克斯 专享 古巴 停产" [ref=e303] [cursor=pointer]:
            - /url: /brand/j-j-fox-exclusives/
            - img "J.J·福克斯 专享" [ref=e305]
            - generic [ref=e306]: J.J·福克斯 专享
            - generic [ref=e307]: 古巴 停产
          - link "皇冠雪茄 皇冠雪茄 古巴 停产" [ref=e308] [cursor=pointer]:
            - /url: /brand/la-corona/
            - img "皇冠雪茄" [ref=e310]
            - generic [ref=e311]: 皇冠雪茄
            - generic [ref=e312]: 古巴 停产
          - link "拉雅仕帕西安 拉雅仕帕西安 古巴 停产" [ref=e313] [cursor=pointer]:
            - /url: /brand/la-escepcion/
            - img "拉雅仕帕西安" [ref=e315]
            - generic [ref=e316]: 拉雅仕帕西安
            - generic [ref=e317]: 古巴 停产
          - link "拉弗洛德卡妮 拉弗洛德卡妮 古巴 停产" [ref=e318] [cursor=pointer]:
            - /url: /brand/la-flor-del-caney/
            - img "拉弗洛德卡妮" [ref=e320]
            - generic [ref=e321]: 拉弗洛德卡妮
            - generic [ref=e322]: 古巴 停产
          - link "劳斯登徒 劳斯登徒 古巴 停产" [ref=e323] [cursor=pointer]:
            - /url: /brand/los-statos-de-luxe/
            - img "劳斯登徒" [ref=e325]
            - generic [ref=e326]: 劳斯登徒
            - generic [ref=e327]: 古巴 停产
          - link "玛丽亚 格雷多 玛丽亚 格雷多 古巴 停产" [ref=e328] [cursor=pointer]:
            - /url: /brand/maria-guerrero/
            - img "玛丽亚 格雷多" [ref=e330]
            - generic [ref=e331]: 玛丽亚 格雷多
            - generic [ref=e332]: 古巴 停产
          - link "新路易斯雷伊 新路易斯雷伊 古巴 停产" [ref=e333] [cursor=pointer]:
            - /url: /brand/san-luis-rey/
            - img "新路易斯雷伊" [ref=e335]
            - generic [ref=e336]: 新路易斯雷伊
            - generic [ref=e337]: 古巴 停产
          - link "西波妮 西波妮 古巴 停产" [ref=e338] [cursor=pointer]:
            - /url: /brand/siboney/
            - img "西波妮" [ref=e340]
            - generic [ref=e341]: 西波妮
            - generic [ref=e342]: 古巴 停产