- generic [active] [ref=e1]:
  - banner [ref=e2]:
    - generic [ref=e3]:
      - generic [ref=e4]: MC
      - generic [ref=e5]: CigarDomTabaka
      - generic [ref=e6]: · Cohiba
    - navigation [ref=e7]:
      - link "品牌" [ref=e8] [cursor=pointer]:
        - /url: /
        - img [ref=e9]
        - text: 品牌
    - link "登录" [ref=e12] [cursor=pointer]:
      - /url: /login/
  - main [ref=e13]:
    - generic [ref=e14]:
      - link "所有品牌" [ref=e15] [cursor=pointer]:
        - /url: /
      - text: /
      - link "高希霸" [ref=e16] [cursor=pointer]:
        - /url: /brand/cohiba/
      - text: / 特级皇冠
    - main [ref=e17]:
      - generic [ref=e18]:
        - generic [ref=e19] [cursor=pointer]:
          - text: 古巴
          - img "特级皇冠" [ref=e20]
        - generic [ref=e21]:
          - heading "特级皇冠" [level=1] [ref=e22]
          - generic [ref=e23]: Coronas Especiales
          - generic [ref=e24]: 古巴 常规生产
          - generic [ref=e25]:
            - generic [ref=e26]:
              - generic [ref=e27]: 尺寸
              - generic [ref=e28]: 152mm × ⌀38
            - generic [ref=e29]:
              - generic [ref=e30]: 型号
              - generic [ref=e31]: 拉吉托 2号
              - generic [ref=e32]: Laguito No.2
            - generic [ref=e33]:
              - generic [ref=e34]: 规格
              - generic [ref=e35]: 特级皇冠
              - generic [ref=e36]: Panetela
      - generic [ref=e37]:
        - generic [ref=e38]: 规格详情
        - generic [ref=e39]:
          - generic [ref=e40]:
            - generic [ref=e41]: 长度
            - generic [ref=e42]: 152 mm
          - generic [ref=e43]:
            - generic [ref=e44]: 环径
            - generic [ref=e45]: ⌀ 38
          - generic [ref=e46]:
            - generic [ref=e47]: 常见名称
            - generic [ref=e48]: 特级皇冠
            - generic [ref=e49]: Panetela
          - generic [ref=e50]:
            - generic [ref=e51]: 工厂型号
            - generic [ref=e52]: 拉吉托 2号
            - generic [ref=e53]: Laguito No.2
      - generic [ref=e54]:
        - generic [ref=e55]: 包装规格
        - list [ref=e57]:
          - listitem [ref=e58]: 漆面自然盒，25 支
          - listitem [ref=e59]: 展示盒，25 支，内含 5 个纸盒 × 5 支（2017 年停产）
          - listitem [ref=e60]: 纸盒，3 支 (discontinued pre-2000s)
          - listitem [ref=e61]: 漆面自然盒，25 支 套玻璃纸 (discontinued pre-2000s)
          - listitem [ref=e62]: 漆面自然盒，50 支 (discontinued pre-2000s)
          - listitem [ref=e63]: 漆面自然盒，50 支 套玻璃纸 (discontinued pre-2000s)
          - listitem [ref=e64]: 木盒，25 支（约 1982 年停产）
          - listitem [ref=e65]: 木盒，50 支（约 1982 年停产）
      - generic [ref=e66]:
        - generic [ref=e67]: 图片 (1 张)
        - generic [ref=e68]:
          - heading "产品图 (1)" [level=3] [ref=e69]
          - generic [ref=e71]:
            - text: 主图
            - img "Coronas Especiales" [ref=e73]
            - generic [ref=e74]: 产品图
      - separator [ref=e75]
      - generic [ref=e76]:
        - generic [ref=e77]: 同品牌更多雪茄
        - generic [ref=e78]:
          - link "导师 珍藏系列" [ref=e79] [cursor=pointer]:
            - /url: /cigar/144/
            - generic [ref=e80]:
              - generic [ref=e81]: 导师
              - generic [ref=e82]: 珍藏系列
          - link "特级皇冠 珍藏系列" [ref=e83] [cursor=pointer]:
            - /url: /cigar/143/
            - generic [ref=e84]:
              - generic [ref=e85]: 特级皇冠
              - generic [ref=e86]: 珍藏系列
          - link "琥珀 快乐" [ref=e87] [cursor=pointer]:
            - /url: /cigar/111/
            - generic [ref=e89]:
              - generic [ref=e90]: 琥珀
              - generic [ref=e91]: 快乐
          - link "世纪 4 号 粗皇冠" [ref=e92] [cursor=pointer]:
            - /url: /cigar/99/
            - generic [ref=e93]:
              - generic [ref=e94]: 世纪 4 号
              - generic [ref=e95]: 粗皇冠
          - link "金 金字塔 纪念发行" [ref=e96] [cursor=pointer]:
            - /url: /cigar/132/
            - generic [ref=e97]: 金
            - generic [ref=e98]:
              - generic [ref=e99]: 金字塔
              - generic [ref=e100]: 纪念发行
          - link "贝伊可 54 拉吉托 5号" [ref=e101] [cursor=pointer]:
            - /url: /cigar/106/
            - generic [ref=e103]:
              - generic [ref=e104]: 贝伊可 54
              - generic [ref=e105]: 拉吉托 5号
          - link "俱乐部 2024年版 Limited Edition Series" [ref=e106] [cursor=pointer]:
            - /url: /cigar/1306/
            - generic [ref=e107]:
              - generic [ref=e108]: 俱乐部 2024年版
              - generic [ref=e109]: Limited Edition Series
          - link "世 世纪 2 号 纪念发行" [ref=e110] [cursor=pointer]:
            - /url: /cigar/124/
            - generic [ref=e111]: 世
            - generic [ref=e112]:
              - generic [ref=e113]: 世纪 2 号
              - generic [ref=e114]: 纪念发行
    - generic:
      - button "✕"