# Generated by Django 6.0.1 on 2026-04-25 17:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cigar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('name', models.CharField(max_length=200, verbose_name='品名')),
                ('vitola', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='长度 (mm)')),
                ('ring_gauge', models.FloatField(blank=True, null=True, verbose_name='环径')),
                ('common_name', models.CharField(blank=True, max_length=100, verbose_name='常见名称')),
                ('status', models.CharField(default='Current', max_length=50, verbose_name='状态')),
                ('url', models.URLField(blank=True, verbose_name='产品页URL')),
                ('packagings', models.TextField(blank=True, help_text='JSON数组: [{"size":25,"type":"Varnished boîte nature box","discontinued":false},...]', verbose_name='包装信息JSON')),
                ('image_url', models.URLField(blank=True, verbose_name='图片URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cigars/', verbose_name='本地图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '雪茄',
                'verbose_name_plural': '雪茄',
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='原始数量')),
                ('remaining', models.IntegerField(verbose_name='剩余数量')),
                ('unit_cost_cny', models.FloatField(verbose_name='人民币成本单价')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='进货日期')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cigars.cigar', verbose_name='雪茄')),
            ],
            options={
                'verbose_name': '进货批次',
                'verbose_name_plural': '进货批次',
                'ordering': ['purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DAMAGE', '破损'), ('GIFT', '送人'), ('LOSS', '丢失')], max_length=20, verbose_name='类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_cost_cny', models.FloatField(verbose_name='成本/支 (CNY)')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cigars.cigar', verbose_name='雪茄')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cigars.purchasebatch', verbose_name='关联批次')),
            ],
            options={
                'verbose_name': '库存修正',
                'verbose_name_plural': '库存修正',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rub_total', models.FloatField(verbose_name='卢布总额')),
                ('exchange_rate', models.FloatField(verbose_name='汇率 (RUB→CNY)')),
                ('cny_total', models.FloatField(verbose_name='人民币总额')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('locked', models.BooleanField(default=False, verbose_name='已锁定')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='锁定人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '进货单',
                'verbose_name_plural': '进货单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('box_size', models.IntegerField(blank=True, help_text='如25=木盒25支, 15=铝管15支, 从Cigar.packagings可查盒型', null=True, verbose_name='包装支数')),
                ('unit_price_rub', models.FloatField(verbose_name='卢布单价')),
                ('unit_price_cny', models.FloatField(verbose_name='人民币单价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cigars.cigar', verbose_name='雪茄')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cigars.purchaseorder', verbose_name='进货单')),
            ],
            options={
                'verbose_name': '进货明细',
                'verbose_name_plural': '进货明细',
            },
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='purchase_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='cigars.purchaseorderitem', verbose_name='进货明细'),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='散客名')),
                ('total_revenue', models.FloatField(default=0, verbose_name='收入合计')),
                ('total_cost', models.FloatField(default=0, verbose_name='成本合计')),
                ('total_profit', models.FloatField(default=0, verbose_name='利润合计')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('locked', models.BooleanField(default=False, verbose_name='已锁定')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cigars.customer', verbose_name='客户')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='锁定人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '销售单',
                'verbose_name_plural': '销售单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.FloatField(verbose_name='售价/支 (CNY)')),
                ('unit_cost', models.FloatField(verbose_name='成本/支 (CNY)')),
                ('revenue', models.FloatField(verbose_name='收入')),
                ('cost', models.FloatField(verbose_name='成本')),
                ('profit', models.FloatField(verbose_name='利润')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cigars.cigar', verbose_name='雪茄')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cigars.salesorder', verbose_name='销售单')),
            ],
            options={
                'verbose_name': '销售明细',
                'verbose_name_plural': '销售明细',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cigars.supplier', verbose_name='供应商'),
        ),
        migrations.AddIndex(
            model_name='purchasebatch',
            index=models.Index(fields=['cigar', 'remaining'], name='cigars_purc_cigar_i_9b513d_idx'),
        ),
    ]
