# Generated by Django 6.0.1 on 2026-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0001_add_cigar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigar',
            name='release_type',
            field=models.CharField(blank=True, help_text='如 Edición Limitada, La Casa del Habano Exclusivo', max_length=100, verbose_name='特别款类型'),
        ),
    ]
