# Generated by Django 6.0.1 on 2026-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0002_add_release_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cigar',
            unique_together={('brand', 'name', 'release_type')},
        ),
    ]
