# Generated by Django 6.0.1 on 2026-04-26 15:41

import cigars.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0003_unique_brand_name_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='CigarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cigars.models.cigar_image_path, verbose_name='原图')),
                ('thumbnail', models.ImageField(blank=True, upload_to=cigars.models.cigar_thumb_path, verbose_name='缩略图')),
                ('image_type', models.CharField(choices=[('cigar', '产品图'), ('band', '茄标'), ('packaging', '包装'), ('special', '特殊包装')], max_length=20, verbose_name='图片类型')),
                ('image_url', models.URLField(blank=True, verbose_name='原始URL')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主图')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cigars.cigar', verbose_name='雪茄')),
            ],
            options={
                'verbose_name': '雪茄图片',
                'verbose_name_plural': '雪茄图片',
                'ordering': ['cigar', 'order'],
            },
        ),
    ]
