# Generated by Django 6.0.1 on 2026-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0004_add_cigar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigar',
            name='origin',
            field=models.CharField(choices=[('Cuban', '古巴'), ('Non-Cuban', '非古巴'), ('Unknown', '未知')], default='Cuban', max_length=20, verbose_name='产地'),
        ),
    ]
