# Generated by Django 6.0.1 on 2026-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0005_add_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigar',
            name='origin',
            field=models.CharField(choices=[('Cuban', '古巴'), ('Dominican', '多米尼加'), ('Nicaraguan', '尼加拉瓜'), ('Honduran', '洪都拉斯'), ('Mexican', '墨西哥'), ('American', '美国'), ('Chinese', '中国'), ('Indonesian', '印尼'), ('Other', '其他'), ('Unknown', '未知')], default='Cuban', max_length=20, verbose_name='产地'),
        ),
    ]
