# Generated by Django 6.0.1 on 2026-04-27 07:42

import cigars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0006_alter_cigar_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品牌名')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='标识')),
                ('logo', models.ImageField(blank=True, upload_to=cigars.models.brand_logo_path, verbose_name='品牌LOGO')),
                ('logo_url', models.URLField(blank=True, verbose_name='LOGO原始URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['name'],
            },
        ),
    ]
