# Generated by Django 6.0.1 on 2026-04-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0007_add_brand_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('global', '全球品牌'), ('value', '价值品牌'), ('volume', '走量品牌'), ('other', '其他品牌'), ('ict', 'ICT 机制'), ('special', '特殊品牌'), ('discontinued', '已停产')], default='other', max_length=20, verbose_name='品牌分类'),
        ),
        migrations.AddField(
            model_name='brand',
            name='origin',
            field=models.CharField(choices=[('Cuban', '古巴'), ('Dominican', '多米尼加'), ('Nicaraguan', '尼加拉瓜'), ('Honduran', '洪都拉斯'), ('Other', '其他')], default='Cuban', max_length=20, verbose_name='品牌产地'),
        ),
    ]
