# Generated by Django 6.0.1 on 2026-04-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0009_rename_name_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigar',
            name='release_type_cn',
            field=models.CharField(blank=True, max_length=100, verbose_name='特别款类型（中文）'),
        ),
    ]
