# Generated by Django 6.0.1 on 2026-04-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0010_add_release_type_cn'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigar',
            name='common_name_cn',
            field=models.CharField(blank=True, help_text='通用名中译 (如 Robusto → 罗布图)', max_length=100, verbose_name='常见名称（中文）'),
        ),
        migrations.AddField(
            model_name='cigar',
            name='vitola_cn',
            field=models.CharField(blank=True, help_text='工厂名中译 (如 Laguito No.2 → 拉吉托 2 号)', max_length=100, verbose_name='型号（中文）'),
        ),
    ]
