# Generated by Django 5.2.13 on 2026-05-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0011_vitola_common_name_cn'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigar',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='特别款关联的同名常规款（如 Wide Churchills 特级珍藏 → Wide Churchills 常规）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_editions', to='cigars.cigar', verbose_name='父款式'),
        ),
    ]
