# Generated by Django 5.2.13 on 2026-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0012_cigar_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cigar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cigar',
            name='release_name',
            field=models.CharField(blank=True, help_text='保湿盒/精选集名称，如 Las Tres Coronas Selección。跨保湿盒区分同名雪茄', max_length=200, verbose_name='发布名称'),
        ),
        migrations.AlterUniqueTogether(
            name='cigar',
            unique_together={('brand', 'english_name', 'release_type', 'release_name')},
        ),
    ]
