# Generated by Django 6.0.1 on 2026-05-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0013_add_release_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigar',
            name='production_method',
            field=models.CharField(blank=True, choices=[('', '未标注'), ('machine_rolled', '機捲'), ('hand_rolled', '手捲'), ('machine_rolled_short_filler', '機捲短芯'), ('hand_rolled_long_filler', '手捲長芯')], default='', help_text='机制/手捲，小雪茄多为機捲短芯', max_length=30, verbose_name='制作方式'),
        ),
    ]
