# Generated by Django 6.0.1 on 2026-06-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0014_cigar_production_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='payment_manual',
            field=models.JSONField(blank=True, default=dict, help_text='{"bank_name":"...","card_number":"...","card_holder":"..."}', verbose_name='手动收款信息'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_method_id',
            field=models.IntegerField(blank=True, help_text='引用 PaymentMethod.id', null=True, verbose_name='收款方式ID'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_payment', '待付款'), ('paid', '已付款'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
