# Generated by Django 6.0.1 on 2026-06-03 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0015_salesorder_payment_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
