# Generated by Django 6.0.1 on 2026-06-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0016_salesorder_operator_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CigarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_size', models.IntegerField(verbose_name='包装支数')),
                ('wholesale_price', models.IntegerField(help_text='人民币批发价', verbose_name='批发价/盒(CNY)')),
                ('retail_price', models.IntegerField(blank=True, null=True, verbose_name='零售价/盒(CNY)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cigars.cigar')),
            ],
            options={
                'verbose_name': '雪茄定价',
                'verbose_name_plural': '雪茄定价',
                'ordering': ['sort_order', 'cigar__brand', 'cigar__english_name'],
                'unique_together': {('cigar', 'box_size')},
            },
        ),
    ]
