# Generated by Django 6.0.1 on 2026-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0017_cigarprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigarprice',
            name='can_preorder',
            field=models.BooleanField(default=False, verbose_name='可预购'),
        ),
    ]
