# Generated by Django 6.0.6 on 2026-08-11 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_ledgerposting_category_and_more'),
        ('cigars', '0022_purchase_order_status_and_habanos_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebatch',
            name='physical_remaining',
            field=models.IntegerField(default=0, verbose_name='物理剩余数量'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='remaining_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='剩余人民币成本池'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='sold_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计销售成本'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='actual_transport_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='实际人肉成本 (CNY)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='amount_due_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='应收总额 (CNY)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contribution_profit_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='订单贡献利润 (CNY)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_transport_fee_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='客户人肉费 (CNY)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='fifo_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='FIFO 销售成本 (CNY)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='fulfillment_status',
            field=models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认/已预留'), ('shipped', '已出库'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='履约状态'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='goods_amount_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='商品金额 (CNY)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未收款'), ('paid', '已收款'), ('refund_pending', '待退款'), ('refunded', '已退款')], default='unpaid', max_length=20, verbose_name='收款状态'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='box_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='包装支数'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sale_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='销售数量'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sale_unit',
            field=models.CharField(blank=True, choices=[('box', '盒'), ('stick', '支')], default='', max_length=10, verbose_name='销售单位'),
        ),
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='收款金额 (CNY)')),
                ('business_date', models.DateField(verbose_name='业务日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fund_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='accounting.fundaccount', verbose_name='收款资金账户')),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipt', to='accounting.ledgertransaction', verbose_name='账务交易')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipt', to='cigars.salesorder', verbose_name='销售单')),
            ],
            options={
                'verbose_name': '销售收款',
                'verbose_name_plural': '销售收款',
            },
        ),
        migrations.CreateModel(
            name='SalesShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(verbose_name='业务日期')),
                ('fifo_cost_cny', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='FIFO 成本 (CNY)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_shipment', to='accounting.ledgertransaction', verbose_name='账务交易')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_shipments', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_shipment', to='cigars.salesorder', verbose_name='销售单')),
            ],
            options={
                'verbose_name': '销售出库',
                'verbose_name_plural': '销售出库',
            },
        ),
        migrations.CreateModel(
            name='SalesTransportCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_cost_cny', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='实际人肉成本 (CNY)')),
                ('business_date', models.DateField(verbose_name='业务日期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fund_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_transport_costs', to='accounting.fundaccount', verbose_name='付款资金账户')),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_transport_cost', to='accounting.ledgertransaction', verbose_name='账务交易')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_transport_costs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_transport_cost', to='cigars.salesorder', verbose_name='销售单')),
            ],
            options={
                'verbose_name': '销售人肉成本',
                'verbose_name_plural': '销售人肉成本',
            },
        ),
    ]
