# Generated by Django 6.0.6 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0024_backfill_purchase_batch_inventory_facts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='purchase_batch_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='purchase_batch_remaining_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('physical_remaining__gte', 0)), name='purchase_batch_physical_remaining_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__lte', models.F('physical_remaining'))), name='purchase_batch_remaining_lte_physical'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('physical_remaining__lte', models.F('quantity'))), name='purchase_batch_physical_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_cost_cny__gte', 0)), name='purchase_batch_remaining_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('sold_cost_cny__gte', 0)), name='purchase_batch_sold_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('goods_amount_cny__gte', 0)), name='sales_order_goods_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('customer_transport_fee_cny__gte', 0)), name='sales_order_customer_transport_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_due_cny__gte', 0)), name='sales_order_amount_due_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('fifo_cost_cny__gte', 0)), name='sales_order_fifo_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('actual_transport_cost_cny__gte', 0)), name='sales_order_actual_transport_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('sale_quantity__isnull', True), ('sale_quantity__gt', 0), _connector='OR'), name='sales_item_sale_quantity_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('box_size__isnull', True), ('box_size__gt', 0), _connector='OR'), name='sales_item_box_size_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='salesshipment',
            constraint=models.CheckConstraint(condition=models.Q(('fifo_cost_cny__gte', 0)), name='sales_shipment_fifo_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cny__gt', 0)), name='sales_receipt_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salestransportcost',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost_cny__gte', 0)), name='sales_transport_cost_actual_gte_zero'),
        ),
    ]
