# Generated by Django 6.0.6 on 2026-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0025_purchasebatch_purchase_batch_quantity_gte_zero_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_cny__gte', 0)), name='purchase_batch_unit_cost_gte_zero'),
        ),
    ]
