# Generated by Django 6.0.6 on 2026-08-11
from decimal import Decimal

from django.db import migrations, models
from django.db.models import F, Q


def _decimal(value):
    return value if isinstance(value, Decimal) else Decimal(str(value))


def backfill_purchase_batch_cost_facts(apps, schema_editor):
    PurchaseBatch = apps.get_model('cigars', 'PurchaseBatch')
    StockMovement = apps.get_model('cigars', 'StockMovement')
    AdjustmentRecord = apps.get_model('cigars', 'AdjustmentRecord')

    positive_adjustments_by_batch = {}
    for movement in StockMovement.objects.filter(
        movement_type='adjustment', quantity__gt=0, purchase_batch__isnull=False,
    ).iterator():
        positive_adjustments_by_batch[movement.purchase_batch_id] = (
            positive_adjustments_by_batch.get(movement.purchase_batch_id, 0) + movement.quantity
        )

    adjustment_cost_by_batch = {}
    for adjustment in AdjustmentRecord.objects.all().iterator():
        unit_cost_cny = _decimal(adjustment.unit_cost_cny)
        cost_cny = Decimal(adjustment.quantity) * unit_cost_cny
        if adjustment.quantity < 0 or unit_cost_cny < 0 or cost_cny < 0:
            raise RuntimeError(
                f'采购批次 {adjustment.batch_id} 的损耗记录 {adjustment.pk} 存在负成本，无法回填成本事实'
            )
        AdjustmentRecord.objects.filter(pk=adjustment.pk).update(cost_cny=cost_cny)
        if adjustment.batch_id is not None:
            adjustment_cost_by_batch[adjustment.batch_id] = (
                adjustment_cost_by_batch.get(adjustment.batch_id, Decimal('0')) + cost_cny
            )

    for batch in PurchaseBatch.objects.select_related('purchase_order_item').all().iterator():
        original_quantity = batch.purchase_order_item.quantity
        positive_adjustment_quantity = positive_adjustments_by_batch.get(batch.pk, 0)
        unit_cost_cny = _decimal(batch.unit_cost_cny)
        original_cost_cny = Decimal(original_quantity) * unit_cost_cny
        positive_adjustment_cost_cny = Decimal(positive_adjustment_quantity) * unit_cost_cny
        adjustment_cost_cny = adjustment_cost_by_batch.get(batch.pk, Decimal('0'))
        remaining_cost_cny = _decimal(batch.remaining_cost_cny)
        sold_cost_cny = _decimal(batch.sold_cost_cny)

        if (
            original_quantity < 0
            or positive_adjustment_quantity < 0
            or unit_cost_cny < 0
            or original_cost_cny < 0
            or positive_adjustment_cost_cny < 0
            or adjustment_cost_cny < 0
        ):
            raise RuntimeError(f'采购批次 {batch.pk} 存在负数量或成本，无法回填成本事实')
        if not (0 <= batch.remaining <= batch.physical_remaining <= original_quantity + positive_adjustment_quantity):
            raise RuntimeError(f'采购批次 {batch.pk} 的库存数量不守恒，无法回填成本事实')
        if original_cost_cny + positive_adjustment_cost_cny != (
            remaining_cost_cny + sold_cost_cny + adjustment_cost_cny
        ):
            raise RuntimeError(f'采购批次 {batch.pk} 的成本不守恒，无法回填成本事实')

        PurchaseBatch.objects.filter(pk=batch.pk).update(
            quantity=original_quantity,
            positive_adjustment_quantity=positive_adjustment_quantity,
            original_cost_cny=original_cost_cny,
            positive_adjustment_cost_cny=positive_adjustment_cost_cny,
            adjustment_cost_cny=adjustment_cost_cny,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0026_purchase_batch_unit_cost_gte_zero'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchasebatch',
            name='purchase_batch_physical_lte_quantity',
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='original_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='原始入库人民币成本'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='positive_adjustment_quantity',
            field=models.IntegerField(default=0, verbose_name='正向调整数量'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='positive_adjustment_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='正向调整人民币成本'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='adjustment_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='累计损耗人民币成本'),
        ),
        migrations.AddField(
            model_name='adjustmentrecord',
            name='cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='损耗总成本 (CNY)'),
        ),
        migrations.RunPython(backfill_purchase_batch_cost_facts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(positive_adjustment_quantity__gte=0), name='purchase_batch_positive_adjustment_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(physical_remaining__lte=F('quantity') + F('positive_adjustment_quantity')), name='purchase_batch_physical_lte_capacity'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(original_cost_cny__gte=0), name='purchase_batch_original_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(positive_adjustment_cost_cny__gte=0), name='purchase_batch_positive_adjustment_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(adjustment_cost_cny__gte=0), name='purchase_batch_adjustment_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrecord',
            constraint=models.CheckConstraint(condition=Q(cost_cny__gte=0), name='adjustment_record_cost_gte_zero'),
        ),
    ]
