# Generated by Django 6.0.6 on 2026-08-11
from decimal import Decimal

from django.db import migrations, models
from django.db.models import F, Q, Sum


def _decimal(value):
    return value if isinstance(value, Decimal) else Decimal(str(value))


def backfill_purchase_batch_cost_facts(apps, schema_editor):
    PurchaseBatch = apps.get_model('cigars', 'PurchaseBatch')
    StockMovement = apps.get_model('cigars', 'StockMovement')
    StockAllocation = apps.get_model('cigars', 'StockAllocation')
    AdjustmentRecord = apps.get_model('cigars', 'AdjustmentRecord')
    opening_receive_by_batch = {}
    normal_receive_by_batch = {}
    batches = list(PurchaseBatch.objects.select_related('purchase_order_item').all())
    batch_by_id = {batch.pk: batch for batch in batches}



    positive_adjustments_by_batch = {}
    for movement in StockMovement.objects.filter(
        movement_type='adjustment', quantity__gt=0, purchase_batch__isnull=False,
    ).iterator():
        positive_adjustments_by_batch[movement.purchase_batch_id] = (
            positive_adjustments_by_batch.get(movement.purchase_batch_id, 0) + movement.quantity
        )

    negative_adjustments_by_batch = {}
    for movement in StockMovement.objects.filter(
        movement_type='adjustment', quantity__lt=0, purchase_batch__isnull=False,
    ).iterator():
        negative_adjustments_by_batch[movement.purchase_batch_id] = (
            negative_adjustments_by_batch.get(movement.purchase_batch_id, 0) - movement.quantity
        )

    shipment_by_batch = {}
    allowed_movement_types = {
        'receive', 'reserve', 'release_reservation', 'ship', 'adjustment',
    }
    for movement in StockMovement.objects.filter(purchase_batch__isnull=False).iterator():
        batch_id = movement.purchase_batch_id
        batch = batch_by_id[batch_id]
        if movement.cigar_id != batch.cigar_id:
            raise RuntimeError(f'采购批次 {batch_id} 的库存流水 {movement.pk} 雪茄与批次不一致')
        if movement.movement_type not in allowed_movement_types:
            raise RuntimeError(f'采购批次 {batch_id} 存在未知库存流水类型')
        if movement.quantity == 0:
            raise RuntimeError(f'采购批次 {batch_id} 存在零数量库存流水')
        if movement.quantity < 0 and movement.movement_type != 'adjustment':
            raise RuntimeError(f'采购批次 {batch_id} 存在非法负数量库存流水')
        if movement.movement_type == 'receive':
            receives = opening_receive_by_batch if (
                movement.command_name == 'migration_stock_opening_balance'
            ) else normal_receive_by_batch
            receives[batch_id] = receives.get(batch_id, 0) + movement.quantity
        if movement.movement_type == 'ship':
            shipment_by_batch[batch_id] = shipment_by_batch.get(batch_id, 0) + movement.quantity

    adjustment_cost_by_batch = {}
    adjustment_quantity_by_batch = {}
    adjustment_updates = []
    for adjustment in AdjustmentRecord.objects.all().iterator():
        unit_cost_cny = _decimal(adjustment.unit_cost_cny)
        cost_cny = Decimal(adjustment.quantity) * unit_cost_cny
        if adjustment.quantity < 0 or unit_cost_cny < 0 or cost_cny < 0:
            raise RuntimeError(
                f'采购批次 {adjustment.batch_id} 的损耗记录 {adjustment.pk} 存在负成本，无法回填成本事实'
            )
        if adjustment.batch_id is not None and adjustment.cigar_id != batch_by_id[adjustment.batch_id].cigar_id:
            raise RuntimeError(f'采购批次 {adjustment.batch_id} 的损耗记录 {adjustment.pk} 雪茄与批次不一致')

        adjustment.cost_cny = cost_cny
        adjustment_updates.append(adjustment)
        if adjustment.batch_id is not None:
            adjustment_cost_by_batch[adjustment.batch_id] = (
                adjustment_cost_by_batch.get(adjustment.batch_id, Decimal('0')) + cost_cny
            )
            adjustment_quantity_by_batch[adjustment.batch_id] = (
                adjustment_quantity_by_batch.get(adjustment.batch_id, 0) + adjustment.quantity
            )

    allocation_facts_by_batch = {}
    allowed_allocation_statuses = {'reserved', 'fulfilled', 'released'}
    for allocation in StockAllocation.objects.all().iterator():
        batch_id = allocation.purchase_batch_id
        batch = batch_by_id[batch_id]
        if allocation.sales_order_item.cigar_id != batch.cigar_id:
            raise RuntimeError(f'采购批次 {batch_id} 的库存分配 {allocation.pk} 雪茄与批次不一致')
        if allocation.status not in allowed_allocation_statuses:
            raise RuntimeError(f'采购批次 {batch_id} 存在未知库存分配状态')
        if allocation.quantity <= 0:
            raise RuntimeError(f'采购批次 {batch_id} 存在非正数量库存分配')

        facts = allocation_facts_by_batch.setdefault(
            batch_id,
            {'reserved': 0, 'fulfilled': 0},
        )
        if allocation.status == 'reserved':
            facts['reserved'] += allocation.quantity
        elif allocation.status == 'fulfilled':
            facts['fulfilled'] += allocation.quantity

    allocation_facts_by_batch = {}
    for row in StockAllocation.objects.filter(status__in={'reserved', 'fulfilled'}).values(
        'purchase_batch_id', 'status',
    ).annotate(quantity=Sum('quantity')):
        facts = allocation_facts_by_batch.setdefault(
            row['purchase_batch_id'],
            {'reserved': 0, 'fulfilled': 0},
        )
        facts[row['status']] = row['quantity'] or 0

    # 逐条扫描只用于状态、数量和归属校验；汇总交给数据库按批次完成。

    batch_updates = []
    for batch in batches:
        original_quantity = batch.purchase_order_item.quantity
        opening_receive_quantity = opening_receive_by_batch.get(batch.pk, 0)
        normal_receive_quantity = normal_receive_by_batch.get(batch.pk, 0)
        if opening_receive_quantity and normal_receive_quantity:
            raise RuntimeError(f'采购批次 {batch.pk} 同时存在 opening balance 与正常入库流水')
        if opening_receive_quantity:
            physical_baseline = opening_receive_quantity
        elif normal_receive_quantity:
            if normal_receive_quantity != original_quantity:
                raise RuntimeError(f'采购批次 {batch.pk} 的正常入库流水数量与采购明细不一致')
            physical_baseline = normal_receive_quantity
        else:
            physical_baseline = 0

        positive_adjustment_quantity = positive_adjustments_by_batch.get(batch.pk, 0)
        negative_adjustment_quantity = negative_adjustments_by_batch.get(batch.pk, 0)
        adjustment_record_quantity = adjustment_quantity_by_batch.get(batch.pk, 0)
        shipped_quantity = shipment_by_batch.get(batch.pk, 0)
        allocation_facts = allocation_facts_by_batch.get(
            batch.pk,
            {'reserved': 0, 'fulfilled': 0},
        )
        reserved_quantity = allocation_facts['reserved']
        fulfilled_quantity = allocation_facts['fulfilled']
        unit_cost_cny = _decimal(batch.unit_cost_cny)
        original_cost_cny = Decimal(original_quantity) * unit_cost_cny
        positive_adjustment_cost_cny = Decimal(positive_adjustment_quantity) * unit_cost_cny
        adjustment_cost_cny = adjustment_cost_by_batch.get(batch.pk, Decimal('0'))
        remaining_cost_cny = _decimal(batch.remaining_cost_cny)
        sold_cost_cny = _decimal(batch.sold_cost_cny)
        expected_physical_remaining = (
            physical_baseline
            + positive_adjustment_quantity
            - negative_adjustment_quantity
            - shipped_quantity
        )

        if (
            original_quantity < 0
            or positive_adjustment_quantity < 0
            or negative_adjustment_quantity < 0
            or shipped_quantity < 0
            or reserved_quantity < 0
            or fulfilled_quantity < 0
            or adjustment_record_quantity < 0
            or unit_cost_cny < 0
            or original_cost_cny < 0
            or positive_adjustment_cost_cny < 0
            or adjustment_cost_cny < 0
        ):
            raise RuntimeError(f'采购批次 {batch.pk} 存在负数量或成本，无法回填成本事实')
        if negative_adjustment_quantity != adjustment_record_quantity:
            raise RuntimeError(f'采购批次 {batch.pk} 的负向调整流水与损耗记录数量不一致')
        if shipped_quantity != fulfilled_quantity:
            raise RuntimeError(f'采购批次 {batch.pk} 的出库流水与已出库分配数量不一致')
        if expected_physical_remaining != batch.physical_remaining:
            raise RuntimeError(f'采购批次 {batch.pk} 的物理库存与流水数量不一致')
        if batch.remaining + reserved_quantity != batch.physical_remaining:
            raise RuntimeError(f'采购批次 {batch.pk} 的可用库存与预留数量不等于物理库存')

        if not (0 <= batch.remaining <= batch.physical_remaining <= physical_baseline + positive_adjustment_quantity):
            raise RuntimeError(f'采购批次 {batch.pk} 的库存数量不守恒，无法回填成本事实')
        if original_cost_cny + positive_adjustment_cost_cny != (
            remaining_cost_cny + sold_cost_cny + adjustment_cost_cny
        ):
            raise RuntimeError(f'采购批次 {batch.pk} 的成本不守恒，无法回填成本事实')

        batch.quantity = original_quantity
        batch.positive_adjustment_quantity = positive_adjustment_quantity
        batch.original_cost_cny = original_cost_cny
        batch.positive_adjustment_cost_cny = positive_adjustment_cost_cny
        batch.adjustment_cost_cny = adjustment_cost_cny
        batch_updates.append(batch)

    # 迁移库约千级记录：先完成所有校验，再用两次批量写避免 N+1 update。
    AdjustmentRecord.objects.bulk_update(adjustment_updates, ['cost_cny'], batch_size=500)
    PurchaseBatch.objects.bulk_update(
        batch_updates,
        [
            'quantity', 'positive_adjustment_quantity', 'original_cost_cny',
            'positive_adjustment_cost_cny', 'adjustment_cost_cny',
        ],
        batch_size=500,
    )



class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0026_purchase_batch_unit_cost_gte_zero'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchasebatch',
            name='purchase_batch_physical_lte_quantity',
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='original_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='原始入库人民币成本'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='positive_adjustment_quantity',
            field=models.IntegerField(default=0, verbose_name='正向调整数量'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='positive_adjustment_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='正向调整人民币成本'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='adjustment_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='累计损耗人民币成本'),
        ),
        migrations.AddField(
            model_name='adjustmentrecord',
            name='cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='损耗总成本 (CNY)'),
        ),
        migrations.RunPython(backfill_purchase_batch_cost_facts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(positive_adjustment_quantity__gte=0), name='purchase_batch_positive_adjustment_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(physical_remaining__lte=F('quantity') + F('positive_adjustment_quantity')), name='purchase_batch_physical_lte_capacity'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(original_cost_cny__gte=0), name='purchase_batch_original_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(positive_adjustment_cost_cny__gte=0), name='purchase_batch_positive_adjustment_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=Q(adjustment_cost_cny__gte=0), name='purchase_batch_adjustment_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrecord',
            constraint=models.CheckConstraint(condition=Q(cost_cny__gte=0), name='adjustment_record_cost_gte_zero'),
        ),
    ]
