# Generated by Django 6.0.1 on 2026-08-11 22:13

from django.db import migrations, models



def backfill_packaging_inventory(apps, schema_editor):
    PurchaseBatch = apps.get_model("cigars", "PurchaseBatch")
    StockAllocation = apps.get_model("cigars", "StockAllocation")
    reserved = {}
    for allocation in StockAllocation.objects.filter(status="reserved").select_related("sales_order_item"):
        if allocation.quantity <= 0:
            raise RuntimeError(f'采购批次 {allocation.purchase_batch_id} 存在非正预留分配 {allocation.pk}')
        reserved.setdefault(allocation.purchase_batch_id, []).append(allocation)
    updates = []
    for batch in PurchaseBatch.objects.select_related("purchase_order_item").iterator():
        if batch.quantity < 0 or batch.remaining < 0 or batch.physical_remaining < batch.remaining:
            raise RuntimeError(f'采购批次 {batch.pk} 的库存数量不守恒，无法回填包装事实')
        size = batch.purchase_order_item.box_size
        if size is not None and size <= 0:
            raise RuntimeError(f'采购批次 {batch.pk} 的包装支数非法，无法回填包装事实')
        batch.box_size = size
        allocations = reserved.get(batch.pk, [])
        explained_quantity = batch.remaining + sum(allocation.quantity for allocation in allocations)
        if explained_quantity > batch.physical_remaining:
            raise RuntimeError(f'采购批次 {batch.pk} 的预留数量超过物理库存，无法回填包装事实')
        if size is None:
            batch.original_box_quantity = batch.physical_box_quantity = batch.available_box_quantity = 0
            batch.original_stick_quantity = batch.quantity
            batch.physical_stick_quantity = batch.physical_remaining
            batch.available_stick_quantity = batch.remaining
        else:
            batch.original_box_quantity, batch.original_stick_quantity = divmod(batch.quantity, size)
            batch.available_box_quantity, batch.available_stick_quantity = divmod(batch.remaining, size)
            batch.physical_box_quantity = batch.available_box_quantity
            batch.physical_stick_quantity = batch.available_stick_quantity
            for allocation in allocations:
                item = allocation.sales_order_item
                if item.sale_unit == "box" and item.box_size == size and allocation.quantity % size == 0:
                    batch.physical_box_quantity += allocation.quantity // size
                else:
                    batch.physical_stick_quantity += allocation.quantity
            batch.physical_stick_quantity += batch.physical_remaining - explained_quantity
        updates.append(batch)
    PurchaseBatch.objects.bulk_update(updates, ["box_size", "original_box_quantity", "original_stick_quantity", "physical_box_quantity", "available_box_quantity", "physical_stick_quantity", "available_stick_quantity"])

class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0027_purchase_batch_cost_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebatch',
            name='available_box_quantity',
            field=models.IntegerField(default=0, verbose_name='可用完整盒数'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='available_stick_quantity',
            field=models.IntegerField(default=0, verbose_name='可用散支数'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='box_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='包装支数快照'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='original_box_quantity',
            field=models.IntegerField(default=0, verbose_name='原始完整盒数'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='original_stick_quantity',
            field=models.IntegerField(default=0, verbose_name='原始散支数'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='physical_box_quantity',
            field=models.IntegerField(default=0, verbose_name='物理完整盒数'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='physical_stick_quantity',
            field=models.IntegerField(default=0, verbose_name='物理散支数'),
        ),
        migrations.RunPython(backfill_packaging_inventory, migrations.RunPython.noop),
    ]
