# Generated by Django 6.0.6 on 2026-08-12 01:23

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0030_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='销售单位单价 (CNY)'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('box_size__isnull', False), ('quantity', django.db.models.expressions.CombinedExpression(models.F('sale_quantity'), '*', models.F('box_size'))), ('sale_quantity__isnull', False), ('sale_unit', 'box')), models.Q(('box_size__isnull', True), ('sale_quantity', models.F('quantity')), ('sale_unit', 'stick')), models.Q(('box_size__isnull', True), ('sale_quantity__isnull', True), ('sale_unit', '')), _connector='OR'), name='sales_item_sale_unit_shape_matches_quantity'),
        ),
    ]
