# Generated by Django 6.0.6 on 2026-08-12 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_ledgertransaction_transaction_type'),
        ('cigars', '0031_sales_order_item_sale_unit_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='退款金额 (CNY)')),
                ('business_date', models.DateField(verbose_name='业务日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_refunds', to='accounting.fundaccount', verbose_name='退款资金账户')),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_refund', to='accounting.ledgertransaction', verbose_name='账务交易')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_refunds', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_refund', to='cigars.salesorder', verbose_name='销售单')),
            ],
            options={
                'verbose_name': '销售退款',
                'verbose_name_plural': '销售退款',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cny__gt', 0)), name='sales_refund_amount_gt_zero')],
            },
        ),
    ]
