# Generated by Django 6.0.1 on 2026-08-13 04:39

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0032_salesrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='引导版本')),
                ('auto_show_enabled', models.BooleanField(default=True, verbose_name='自动展示')),
            ],
            options={
                'verbose_name': '引导配置',
                'verbose_name_plural': '引导配置',
            },
        ),
        migrations.CreateModel(
            name='UserGuideProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_version', models.PositiveIntegerField(default=0, verbose_name='已完成版本')),
                ('force_show_next_time', models.BooleanField(default=False, verbose_name='下次强制展示')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户引导进度',
                'verbose_name_plural': '用户引导进度',
            },
        ),
    ]
