# Generated by Django 6.0.6 on 2026-08-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0033_guideconfiguration_userguideprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebatch',
            name='source',
            field=models.CharField(choices=[('purchase', '采购入库'), ('opening', '期初库存')], default='purchase', max_length=12, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='purchasebatch',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='cigars.purchaseorderitem', verbose_name='进货明细'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase_order_item__isnull', False), ('source', 'purchase')), models.Q(('purchase_order_item__isnull', True), ('source', 'opening')), _connector='OR'), name='purchase_batch_source_item_match'),
        ),
    ]
