# Generated by Django 6.0.6 on 2026-08-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0037_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasebatch',
            options={'base_manager_name': 'objects', 'ordering': ['purchased_at'], 'verbose_name': '进货批次', 'verbose_name_plural': '进货批次'},
        ),
        migrations.AlterModelOptions(
            name='stockallocation',
            options={'base_manager_name': 'objects', 'ordering': ['id'], 'verbose_name': '库存分配', 'verbose_name_plural': '库存分配'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'base_manager_name': 'objects', 'ordering': ['-created_at', '-id'], 'verbose_name': '库存流水', 'verbose_name_plural': '库存流水'},
        ),
        migrations.AlterField(
            model_name='stockallocation',
            name='sales_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='cigars.salesorderitem', verbose_name='销售明细'),
        ),
    ]
