# Generated by Django 6.0.6 on 2026-08-16 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_inventory_adjustment_transaction'),
        ('cigars', '0038_alter_purchasebatch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustmentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField(verbose_name='调整数量')),
                ('inventory_form', models.CharField(choices=[('stick', '支'), ('box', '盒')], max_length=8, verbose_name='库存形态')),
                ('business_date', models.DateField(verbose_name='业务日期')),
                ('reason', models.TextField(verbose_name='原因')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='幂等键')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='撤销原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField(verbose_name='批次数量变化')),
                ('box_delta', models.IntegerField(default=0, verbose_name='完整盒变化')),
                ('stick_delta', models.IntegerField(default=0, verbose_name='散支变化')),
                ('cost_delta_cny', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='库存成本变化 (CNY)')),
                ('batch_state_after', models.JSONField(default=dict, verbose_name='动作后批次快照')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='退货销售金额 (CNY)')),
                ('fifo_cost_cny', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='退回库存成本 (CNY)')),
                ('business_date', models.DateField(verbose_name='业务日期')),
                ('reason', models.TextField(verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '销售退货',
                'verbose_name_plural': '销售退货',
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤销入库时间'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='reversed_cost_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='累计撤销入库成本'),
        ),
        migrations.AddField(
            model_name='purchasebatch',
            name='reversed_quantity',
            field=models.IntegerField(default=0, verbose_name='累计撤销入库数量'),
        ),
        migrations.AddField(
            model_name='stockallocation',
            name='box_size_snapshot',
            field=models.IntegerField(blank=True, null=True, verbose_name='盒规快照'),
        ),
        migrations.AddField(
            model_name='stockallocation',
            name='fulfilled_cost_cny',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='出库成本 (CNY)'),
        ),
        migrations.AddField(
            model_name='stockallocation',
            name='inventory_form',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='出库形态快照'),
        ),
        migrations.AddField(
            model_name='stockallocation',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退货时间'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='fulfillment_status',
            field=models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认/已预留'), ('shipped', '已出库'), ('cancelled', '已取消'), ('returned', '已退货')], default='draft', max_length=20, verbose_name='履约状态'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_payment', '待付款'), ('paid', '已付款'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消'), ('returned', '已退货')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stockallocation',
            name='status',
            field=models.CharField(choices=[('reserved', '已预留'), ('fulfilled', '已出库'), ('released', '已释放'), ('returned', '已退货')], default='reserved', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receive', '入库'), ('reserve', '预留'), ('release_reservation', '释放预留'), ('ship', '出库'), ('adjustment', '库存修正'), ('split_box', '拆盒'), ('reverse_receive', '撤销入库'), ('return', '销售退货'), ('reverse_adjustment', '撤销库存调整')], max_length=30, verbose_name='类型'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_quantity__gte', 0)), name='purchase_batch_reversed_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_cost_cny__gte', 0)), name='purchase_batch_reversed_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        reversed_at__isnull=True,
                        reversed_quantity=0,
                        reversed_cost_cny=0,
                    )
                    | models.Q(
                        reversed_at__isnull=False,
                        reversed_quantity=models.F('quantity'),
                        reversed_cost_cny=models.F('original_cost_cny'),
                    )
                ),
                name='purchase_batch_reversal_state_complete',
            ),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentaction',
            name='cigar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_actions', to='cigars.cigar'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentaction',
            name='ledger_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_action', to='accounting.ledgertransaction', verbose_name='原调整交易'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentaction',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentaction',
            name='reversal_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_inventory_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentaction',
            name='reversal_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_reversal', to='accounting.ledgertransaction', verbose_name='撤销交易'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='cigars.inventoryadjustmentaction'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='purchase_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cigars.purchasebatch'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='stock_movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cigars.stockmovement'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='ledger_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return', to='accounting.ledgertransaction', verbose_name='冲正交易'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return', to='cigars.salesorder', verbose_name='销售单'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sales_shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return', to='cigars.salesshipment', verbose_name='原销售出库'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_adjustment_action_delta_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_adjustment_line_delta_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cny__gte', 0)), name='sales_return_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(condition=models.Q(('fifo_cost_cny__gte', 0)), name='sales_return_fifo_cost_gte_zero'),
        ),
    ]
