# Generated by Django 6.0.6 on 2026-08-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0040_purchase_draft_flexibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
