# Generated by Django 6.0.6 on 2026-08-30 15:50

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0041_customer_remark'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseorderitem',
            name='purchase_item_quantity_matches_boxes',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorderitem',
            name='purchase_item_packaging_consistent',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_unit',
            field=models.CharField(choices=[('box', '按盒'), ('stick', '按支')], default='box', max_length=8, verbose_name='采购单位'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_price_rub_per_stick',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='每支卢布价格'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('box_quantity__isnull', True), ('box_size__isnull', True), ('packaging_status', 'review_required'), ('purchase_unit', 'stick'), ('quantity__gte', 0), ('unit_price_rub_per_box__isnull', True), models.Q(('unit_price_rub_per_stick__isnull', True), ('unit_price_rub_per_stick__gte', 0), _connector='OR')), models.Q(('box_quantity__isnull', True), ('box_size__isnull', True), ('packaging_status', 'normalized'), ('purchase_unit', 'stick'), ('quantity__gt', 0), ('unit_price_cny__isnull', True), ('unit_price_rub__isnull', True), ('unit_price_rub_per_box__isnull', True), ('unit_price_rub_per_stick__gte', 0), ('unit_price_rub_per_stick__isnull', False)), models.Q(('packaging_status', 'review_required'), ('purchase_unit', 'box'), models.Q(('box_size__isnull', True), ('box_size__gte', 0), _connector='OR'), models.Q(('box_quantity__isnull', True), ('box_quantity__gte', 0), _connector='OR'), models.Q(('unit_price_rub_per_box__isnull', True), ('unit_price_rub_per_box__gte', 0), _connector='OR')), models.Q(('box_quantity__gt', 0), ('box_quantity__isnull', False), ('box_size__gt', 0), ('box_size__isnull', False), ('packaging_status', 'normalized'), ('purchase_unit', 'box'), ('unit_price_rub_per_box__gte', 0), ('unit_price_rub_per_box__isnull', False)), models.Q(('box_quantity__gt', 0), ('box_quantity__isnull', False), ('box_size__gt', 0), ('box_size__isnull', False), ('packaging_status', 'unrepresentable'), ('purchase_unit', 'box'), ('unit_price_cny__isnull', True), ('unit_price_rub__isnull', True), ('unit_price_rub_per_box__gte', 0), ('unit_price_rub_per_box__isnull', False)), _connector='OR'), name='purchase_item_packaging_consistent'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_rub_per_stick__isnull', True), ('unit_price_rub_per_stick__gte', 0), _connector='OR'), name='purchase_item_stick_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase_unit', 'box'), ('unit_price_rub_per_stick__isnull', True)), models.Q(('box_quantity__isnull', True), ('box_size__isnull', True), ('purchase_unit', 'stick'), ('unit_price_rub_per_box__isnull', True)), _connector='OR'), name='purchase_item_unit_shape_consistent'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('packaging_status', 'review_required'), models.Q(('packaging_status', 'normalized'), ('purchase_unit', 'stick'), ('quantity__gt', 0)), models.Q(('packaging_status__in', ['normalized', 'unrepresentable']), ('purchase_unit', 'box'), ('quantity', django.db.models.expressions.CombinedExpression(models.F('box_size'), '*', models.F('box_quantity')))), _connector='OR'), name='purchase_item_quantity_matches_boxes'),
        ),
    ]
