# Generated by Django 6.0.6 on 2026-09-25 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_dividend_rounds'),
        ('cigars', '0042_remove_purchaseorderitem_purchase_item_quantity_matches_boxes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreceipt',
            options={'base_manager_name': 'objects', 'verbose_name': '销售收款', 'verbose_name_plural': '销售收款'},
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='reversal_ledger_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_sales_receipt', to='accounting.ledgertransaction', verbose_name='收款冲正交易'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='reversal_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_sales_receipts', to=settings.AUTH_USER_MODEL, verbose_name='撤回操作人'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='reversal_reason',
            field=models.TextField(blank=True, verbose_name='撤回原因'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤回时间'),
        ),
        migrations.AlterField(
            model_name='salesreceipt',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='cigars.salesorder', verbose_name='销售单'),
        ),
        migrations.AddConstraint(
            model_name='salesreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('reversed_at__isnull', True)), fields=('sales_order',), name='sales_receipt_one_active_per_order'),
        ),
        migrations.AddConstraint(
            model_name='salesreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_ledger_transaction__isnull', True), ('reversal_operator__isnull', True), ('reversal_reason', ''), ('reversed_at__isnull', True)), models.Q(('reversal_ledger_transaction__isnull', False), ('reversal_operator__isnull', False), ('reversed_at__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='sales_receipt_reversal_fields_consistent'),
        ),
    ]
