# Generated by Django 5.2.13 on 2026-04-27 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cigars', '0010_add_release_type_cn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=12, unique=True)),
                ('html', models.TextField(verbose_name='预渲染HTML')),
                ('viewed', models.BooleanField(default=False, verbose_name='已查看')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privnotes', to='cigars.brand')),
            ],
            options={
                'verbose_name': 'Privnote',
                'verbose_name_plural': 'Privnote',
                'ordering': ['-created_at'],
            },
        ),
    ]
