# Generated by Django 5.2.13 on 2026-04-27 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0010_add_release_type_cn'),
        ('privnote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privnote',
            name='viewed',
        ),
        migrations.AddField(
            model_name='privnote',
            name='burn_after_read',
            field=models.BooleanField(default=True, verbose_name='阅后即焚'),
        ),
        migrations.AddField(
            model_name='privnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='privnote',
            name='has_password',
            field=models.BooleanField(default=False, verbose_name='密码保护'),
        ),
        migrations.AddField(
            model_name='privnote',
            name='max_views',
            field=models.IntegerField(default=1, verbose_name='最大查看次数'),
        ),
        migrations.AddField(
            model_name='privnote',
            name='note_type',
            field=models.CharField(choices=[('catalog', '库存展示'), ('sales', '销售单据')], default='catalog', max_length=10, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='privnote',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='密码哈希'),
        ),
        migrations.AddField(
            model_name='privnote',
            name='title',
            field=models.CharField(default='Untitled', max_length=200, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='privnote',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='已查看次数'),
        ),
        migrations.AlterField(
            model_name='privnote',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privnotes', to='cigars.brand'),
        ),
    ]
