# Generated by Django 6.0.1 on 2026-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privnote', '0002_remove_privnote_viewed_privnote_burn_after_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privnote',
            name='data_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化数据'),
        ),
        migrations.AlterField(
            model_name='privnote',
            name='html',
            field=models.TextField(blank=True, verbose_name='预渲染HTML'),
        ),
    ]
