# Generated by Django 6.0.1 on 2026-06-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigars', '0015_salesorder_payment_manual_and_more'),
        ('privnote', '0003_add_data_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('bank_card', '银行卡'), ('wechat', '微信'), ('alipay', '支付宝')], max_length=20, verbose_name='类型')),
                ('label', models.CharField(help_text='如 "Сбербанк", "微信收款码"', max_length=100, verbose_name='标签')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='银行名')),
                ('card_number', models.CharField(blank=True, max_length=50, verbose_name='卡号')),
                ('card_holder', models.CharField(blank=True, max_length=100, verbose_name='持卡人')),
                ('qr_image', models.ImageField(blank=True, upload_to='payment_qr/', verbose_name='二维码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收款方式',
                'verbose_name_plural': '收款方式',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='privnote',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cigars.salesorder', verbose_name='关联销售单'),
        ),
        migrations.AlterField(
            model_name='privnote',
            name='note_type',
            field=models.CharField(choices=[('inventory', '库存展示'), ('payment', '收款'), ('message', '消息')], default='inventory', max_length=10, verbose_name='类型'),
        ),
    ]
