# Generated by Django 6.0.1 on 2026-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privnote', '0004_paymentmethod_privnote_sales_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='收款备注'),
        ),
    ]
