# Generated by Django 6.0.1 on 2026-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privnote', '0005_paymentmethod_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privnote',
            name='note_type',
            field=models.CharField(choices=[('inventory', '库存展示'), ('payment', '收款'), ('message', '消息'), ('quote', '批发报价')], default='inventory', max_length=10, verbose_name='类型'),
        ),
    ]
