# Generated by Django 6.0.1 on 2026-06-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privnote', '0006_alter_privnote_note_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privnote',
            name='brand',
        ),
    ]
