# Generated by Django 6.0.6 on 2026-08-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_ledgerposting_category_and_more'),
        ('cigars', '0023_purchasebatch_physical_remaining_and_more'),
        ('privnote', '0007_remove_privnote_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='fund_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='accounting.fundaccount', verbose_name='对应资金账户'),
        ),
    ]
