# Generated by Django 6.0.6 on 2026-08-25 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privnote', '0008_paymentmethod_fund_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='收款账号'),
        ),
        migrations.CreateModel(
            name='PaymentMethodAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('deactivate', '停用'), ('activate', '启用')], max_length=20, verbose_name='动作')),
                ('idempotency_key', models.CharField(max_length=255, unique=True, verbose_name='幂等键')),
                ('request_hash', models.CharField(max_length=64, verbose_name='请求摘要')),
                ('response_body', models.JSONField(default=dict, verbose_name='首次响应')),
                ('snapshot', models.JSONField(default=dict, verbose_name='配置快照')),
                ('agent_name', models.CharField(blank=True, default='web', max_length=100, verbose_name='Agent 名称')),
                ('agent_run_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Agent Run ID')),
                ('agent_request_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Agent Request ID')),
                ('command_name', models.CharField(default='privnote.payment_method', max_length=100, verbose_name='命令')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_audits', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='privnote.paymentmethod', verbose_name='收款方式')),
            ],
            options={
                'verbose_name': '收款方式操作记录',
                'verbose_name_plural': '收款方式操作记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
