# Generated by Django 6.0.6 on 2026-09-11 20:20

import django.db.models.deletion
import privnote.models
import privnote.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_expense_category_alter_expense_subcategory_and_more'),
        ('cigars', '0042_remove_purchaseorderitem_purchase_item_quantity_matches_boxes_and_more'),
        ('privnote', '0009_paymentmethod_account_paymentmethodaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='应收金额（CNY）')),
                ('status', models.CharField(choices=[('pending', '待核实'), ('needs_more', '需补充'), ('accepted', '已确认'), ('closed', '已关闭')], default='pending', max_length=16, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='核实时间')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='补充说明')),
                ('closed_reason', models.CharField(blank=True, default='', max_length=100, verbose_name='关闭原因')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('idempotency_key', models.CharField(max_length=255, verbose_name='匿名提交幂等键')),
                ('request_hash', models.CharField(max_length=64, verbose_name='提交摘要')),
                ('fund_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_submissions', to='accounting.fundaccount', verbose_name='入账账户')),
                ('privnote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_submissions', to='privnote.privnote', verbose_name='收款单')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_payment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='核实人')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_submissions', to='cigars.salesorder', verbose_name='销售单')),
                ('sales_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_submission', to='cigars.salesreceipt', verbose_name='正式收款')),
            ],
            options={
                'verbose_name': '付款凭证提交',
                'verbose_name_plural': '付款凭证提交',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=privnote.storage.PrivatePaymentStorage(), upload_to=privnote.models.payment_attachment_upload_to, verbose_name='图片文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(max_length=100, verbose_name='MIME 类型')),
                ('size', models.PositiveIntegerField(verbose_name='文件大小')),
                ('sha256', models.CharField(max_length=64, verbose_name='内容摘要')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='privnote.paymentsubmission', verbose_name='付款凭证提交')),
            ],
            options={
                'verbose_name': '付款凭证图片',
                'verbose_name_plural': '付款凭证图片',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentsubmission',
            index=models.Index(fields=['sales_order', 'status'], name='privnote_pa_sales_o_6bebb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cny__gt', 0)), name='payment_submission_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sales_order',), name='payment_submission_one_pending_per_order'),
        ),
        migrations.AddConstraint(
            model_name='paymentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('sales_order',), name='payment_submission_one_accepted_per_order'),
        ),
        migrations.AddConstraint(
            model_name='paymentsubmission',
            constraint=models.UniqueConstraint(fields=('privnote', 'idempotency_key'), name='payment_submission_privnote_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_reason', ''), ('review_note', ''), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('sales_receipt__isnull', True), ('status', 'pending')), models.Q(('closed_at__isnull', True), ('closed_reason', ''), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('sales_receipt__isnull', True), ('status', 'needs_more'), models.Q(('review_note', ''), _negated=True)), models.Q(('closed_at__isnull', True), ('closed_reason', ''), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('sales_receipt__isnull', False), ('status', 'accepted')), models.Q(('closed_at__isnull', False), ('sales_receipt__isnull', True), ('status', 'closed'), models.Q(('closed_reason', ''), _negated=True)), _connector='OR'), name='payment_submission_lifecycle_valid'),
        ),
    ]
