# Generated by Django 6.0.6 on 2026-09-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privnote', '0010_payment_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivnoteAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitor_key', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=40)),
                ('actor', models.CharField(choices=[('customer', '客户'), ('staff', '员工'), ('bot', '疑似机器人')], max_length=12)),
                ('event', models.CharField(choices=[('open', '成功打开'), ('password_required', '需要密码'), ('password_failed', '密码错误'), ('expired', '已过期'), ('destroyed', '已销毁'), ('closed', '已关闭'), ('error', '打开失败'), ('qr_open', '放大收款二维码'), ('copy_card', '复制卡号'), ('copy_account', '复制收款账号'), ('submission', '提交凭证')], max_length=24)),
                ('dedupe_key', models.CharField(blank=True, max_length=80, null=True)),
                ('privnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='privnote.privnote')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['privnote', 'created_at'], name='pn_access_note_time')],
                'constraints': [models.UniqueConstraint(fields=('privnote', 'dedupe_key'), name='pn_access_dedupe')],
            },
        ),
    ]
