# Generated by Django 5.2.13 on 2026-05-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cigars', '0013_add_release_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('base_url', models.URLField(verbose_name='网站首页')),
                ('scraper_class', models.CharField(help_text='price_tracker/scrapers/ 下的模块名，如 ihavanas', max_length=100, verbose_name='爬虫类名')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='货币')),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='参考汇率（兑CNY）')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='上次抓取')),
                ('scrape_interval_hours', models.IntegerField(default=24, verbose_name='抓取间隔（小时）')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='额外配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '价格来源',
                'verbose_name_plural': '价格来源',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('below', '低于'), ('above', '高于'), ('drop_pct', '跌幅超')], max_length=20, verbose_name='条件')),
                ('target_price', models.FloatField(verbose_name='目标价')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='上次触发')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='cigars.cigar', verbose_name='雪茄')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_tracker.pricesource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '价格预警',
                'verbose_name_plural': '价格预警',
                'ordering': ['cigar', 'source'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='售价')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='货币')),
                ('price_cny', models.FloatField(blank=True, null=True, verbose_name='人民币等值')),
                ('box_size', models.IntegerField(blank=True, null=True, verbose_name='盒装支数')),
                ('box_price', models.FloatField(blank=True, null=True, verbose_name='整盒价')),
                ('url', models.URLField(blank=True, verbose_name='商品页链接')),
                ('in_stock', models.BooleanField(default=True, verbose_name='有货')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_snapshots', to='cigars.cigar', verbose_name='雪茄')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='price_tracker.pricesource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '价格快照',
                'verbose_name_plural': '价格快照',
                'ordering': ['cigar', '-scraped_at'],
                'get_latest_by': 'scraped_at',
                'indexes': [models.Index(fields=['cigar', 'source', '-scraped_at'], name='price_track_cigar_i_b2219a_idx'), models.Index(fields=['source', '-scraped_at'], name='price_track_source__dedcdc_idx')],
            },
        ),
    ]
