# Generated by Django 5.2.13 on 2026-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0002_add_scraped_date_and_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, verbose_name='货币代码')),
                ('rate', models.FloatField(verbose_name='汇率（1单位兑CNY）')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='获取时间')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
                'ordering': ['-date', 'currency'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
