# Generated by Django 5.2.13 on 2026-05-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0003_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesource',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='前端展示用的简短名称，如 COH、LCDH尼翁', max_length=30, verbose_name='简称'),
        ),
    ]
