# Generated by Django 6.0.1 on 2026-05-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0004_add_short_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricesnapshot',
            name='uq_snapshot_per_day',
        ),
    ]
