# Generated by Django 5.2.13 on 2026-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0005_remove_daily_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesnapshot',
            name='original_price',
            field=models.FloatField(blank=True, null=True, verbose_name='原价'),
        ),
    ]
