# Generated by Django 5.2.13 on 2026-06-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0006_add_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesnapshot',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='售价'),
        ),
    ]
