# Generated by Django 5.2.13 on 2026-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0007_allow_null_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesnapshot',
            name='is_anomalous',
            field=models.BooleanField(default=False, help_text='IQR异常检测标记：价格超出同组(cigar_id,box_size)的Q1-3*IQR~Q3+3*IQR范围', verbose_name='价格异常'),
        ),
    ]
