# Generated by Django 6.0.1 on 2026-06-08 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0008_add_is_anomalous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesnapshot',
            name='scraped_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='抓取日期'),
        ),
    ]
