# Generated by Django 6.0.6 on 2026-08-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSequence',
            fields=[
                ('name', models.CharField(default='global', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='账户名称')),
                ('currency', models.CharField(choices=[('CNY', '人民币'), ('RUB', '卢布'), ('USDT', 'USDT')], max_length=4, verbose_name='币种')),
                ('creation_idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='创建幂等键')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodied_fund_accounts', to=settings.AUTH_USER_MODEL, verbose_name='保管人')),
            ],
            options={
                'verbose_name': '资金账户',
                'verbose_name_plural': '资金账户',
                'ordering': ['currency', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('opening_balance', '期初余额'), ('exchange', '换汇'), ('transfer', '同币种转账')], max_length=32, verbose_name='交易类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('posted', '已入账'), ('reversed', '已冲正')], default='draft', max_length=12, verbose_name='状态')),
                ('business_date', models.DateField(verbose_name='业务日期')),
                ('effective_sequence', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='有效顺序')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='幂等键')),
                ('source_type', models.CharField(blank=True, max_length=64, verbose_name='来源类型')),
                ('source_id', models.CharField(blank=True, max_length=128, verbose_name='来源 ID')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='入账时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('reversed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverses', to='accounting.ledgertransaction', verbose_name='冲正交易')),
            ],
            options={
                'verbose_name': '账务交易',
                'verbose_name_plural': '账务交易',
                'ordering': ['business_date', 'effective_sequence', 'id'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(idempotency_key__isnull=True) | ~models.Q(idempotency_key=''),
                        name='accounting_transaction_idempotency_key_not_empty',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='LedgerPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('opening_capital', '期初投入资本'), ('opening_retained_earnings', '期初未分配利润')], max_length=48, verbose_name='内部分类')),
                ('currency', models.CharField(choices=[('CNY', '人民币'), ('RUB', '卢布'), ('USDT', 'USDT')], max_length=4, verbose_name='原币')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='原币金额')),
                ('cny_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='人民币账面金额')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='accounting.fundaccount', verbose_name='资金账户')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='accounting.ledgertransaction', verbose_name='交易')),
            ],
            options={
                'ordering': ['transaction__effective_sequence', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('category', '')), models.Q(('account__isnull', True), models.Q(('category', ''), _negated=True)), _connector='OR'), name='accounting_posting_exactly_one_target')],
            },
        ),
    ]
