# Generated by Django 6.0.6 on 2026-08-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerposting',
            options={'base_manager_name': 'objects', 'ordering': ['transaction__effective_sequence', 'id']},
        ),
        migrations.AlterModelOptions(
            name='ledgertransaction',
            options={'base_manager_name': 'objects', 'ordering': ['business_date', 'effective_sequence', 'id'], 'verbose_name': '账务交易', 'verbose_name_plural': '账务交易'},
        ),
    ]
