# Generated by Django 6.0.6 on 2026-08-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_ledgerposting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundaccount',
            options={'base_manager_name': 'objects', 'ordering': ['currency', 'id'], 'verbose_name': '资金账户', 'verbose_name_plural': '资金账户'},
        ),
        migrations.AlterModelOptions(
            name='ledgersequence',
            options={'base_manager_name': 'objects'},
        ),
    ]
