# Generated by Django 6.0.6 on 2026-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_fundaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerposting',
            name='category',
            field=models.CharField(blank=True, choices=[('opening_capital', '期初投入资本'), ('opening_retained_earnings', '期初未分配利润'), ('accounts_receivable', '应收款'), ('customer_prepayments', '客户预收款'), ('inventory', '库存'), ('sales_revenue', '销售收入'), ('customer_transport_revenue', '客户人肉费收入'), ('cost_of_goods_sold', '销售成本'), ('transport_expense', '人肉费用')], max_length=48, verbose_name='内部分类'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('opening_balance', '期初余额'), ('exchange', '换汇'), ('transfer', '同币种转账'), ('sales_shipment', '销售出库'), ('sales_receipt', '销售收款'), ('sales_transport_cost', '销售人肉费')], max_length=32, verbose_name='交易类型'),
        ),
    ]
