# Generated by Django 6.0.6 on 2026-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_ledgerposting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerposting',
            name='category',
            field=models.CharField(blank=True, choices=[('opening_capital', '期初投入资本'), ('opening_retained_earnings', '期初未分配利润'), ('accounts_receivable', '应收款'), ('customer_prepayments', '客户预收款'), ('inventory', '库存'), ('', '资金账户'), ('sales_revenue', '销售收入'), ('customer_transport_revenue', '客户人肉费收入'), ('cost_of_goods_sold', '销售成本'), ('transport_expense', '人肉费用')], max_length=48, verbose_name='内部分类'),
        ),
    ]
