# Generated by Django 6.0.6 on 2026-08-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_ledgerposting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('opening_balance', '期初余额'), ('exchange', '换汇'), ('transfer', '同币种转账'), ('sales_shipment', '销售出库'), ('sales_receipt', '销售收款'), ('sales_transport_cost', '销售人肉费'), ('sales_refund', '销售退款')], max_length=32, verbose_name='交易类型'),
        ),
    ]
