# Generated by Django 6.0.6 on 2026-08-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_ledgertransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(verbose_name='业务日期')),
                ('system_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='系统余额')),
                ('actual_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='实际余额')),
                ('difference', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='差异')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认')], default='pending', max_length=12, verbose_name='状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.fundaccount', verbose_name='资金账户')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '账户对账',
                'verbose_name_plural': '账户对账',
                'ordering': ['-business_date', '-id'],
                'base_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('account', 'business_date'), name='accounting_reconciliation_account_date_unique')],
            },
        ),
    ]
