# Generated by Django 6.0.6 on 2026-08-13 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountreconciliation_confirmer'),
        ('cigars', '0034_purchase_batch_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day1Initialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='company', editable=False, max_length=20, unique=True, verbose_name='单例键')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '已完成')], default='draft', max_length=12, verbose_name='状态')),
                ('business_date', models.DateField(blank=True, null=True, verbose_name='业务日期')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('completion_summary', models.JSONField(default=dict, verbose_name='完成摘要')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_day1_initializations', to=settings.AUTH_USER_MODEL, verbose_name='完成人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_day1_initializations', to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '期初初始化',
                'verbose_name_plural': '期初初始化',
            },
        ),
        migrations.CreateModel(
            name='Day1DraftInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_size', models.IntegerField(verbose_name='包装支数')),
                ('box_quantity', models.IntegerField(verbose_name='整盒数量')),
                ('loose_sticks', models.IntegerField(verbose_name='散支数量')),
                ('unit_cost_cny', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='人民币单支成本')),
                ('cigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day1_draft_inventory', to='cigars.cigar', verbose_name='雪茄')),
                ('initialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_inventory', to='accounting.day1initialization', verbose_name='期初初始化')),
            ],
            options={
                'verbose_name': '期初库存草稿',
                'verbose_name_plural': '期初库存草稿',
            },
        ),
        migrations.CreateModel(
            name='Day1DraftAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('owner_cny', '老板人民币'), ('partner_cny', '合伙人人民币'), ('rub', '卢布'), ('usdt', 'USDT')], max_length=20, verbose_name='固定槽位')),
                ('account_name', models.CharField(max_length=120, verbose_name='账户名称')),
                ('currency', models.CharField(choices=[('CNY', '人民币'), ('RUB', '卢布'), ('USDT', 'USDT')], max_length=4, verbose_name='币种')),
                ('original_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='原币金额')),
                ('cny_book_cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='人民币账面成本')),
                ('initialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_accounts', to='accounting.day1initialization', verbose_name='期初初始化')),
            ],
            options={
                'verbose_name': '期初资金草稿',
                'verbose_name_plural': '期初资金草稿',
            },
        ),
        migrations.AddConstraint(
            model_name='day1initialization',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_key', 'company')), name='day1_initialization_company_singleton'),
        ),
        migrations.AddConstraint(
            model_name='day1initialization',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='day1_initialization_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='day1initialization',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'completed'])), name='day1_initialization_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='day1draftinventory',
            constraint=models.UniqueConstraint(fields=('initialization', 'cigar', 'box_size'), name='day1_draft_inventory_init_cigar_box_unique'),
        ),
        migrations.AddConstraint(
            model_name='day1draftinventory',
            constraint=models.CheckConstraint(condition=models.Q(('box_size__gt', 0)), name='day1_draft_inventory_box_size_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='day1draftinventory',
            constraint=models.CheckConstraint(condition=models.Q(('box_quantity__gte', 0), ('loose_sticks__gte', 0), ('unit_cost_cny__gte', 0)), name='day1_draft_inventory_values_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='day1draftaccount',
            constraint=models.UniqueConstraint(fields=('initialization', 'slot'), name='day1_draft_account_init_slot_unique'),
        ),
        migrations.AddConstraint(
            model_name='day1draftaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot__in', ['owner_cny', 'partner_cny', 'rub', 'usdt'])), name='day1_draft_account_slot_valid'),
        ),
        migrations.AddConstraint(
            model_name='day1draftaccount',
            constraint=models.CheckConstraint(condition=models.Q(('cny_book_cost__gte', 0), ('original_amount__gte', 0)), name='day1_draft_account_amounts_gte_zero'),
        ),
    ]
