# Generated by Django 6.0.6 on 2026-08-14 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_ledgertransaction_transaction_type'),
        ('cigars', '0036_purchase_payment_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SQLite 对 Decimal 跨字段求和约束支持不稳定；分红两栏求和由服务锁内校验并由终态保护保证。
    operations = [
        migrations.AlterField(
            model_name='ledgerposting',
            name='category',
            field=models.CharField(blank=True, choices=[('opening_capital', '期初投入资本'), ('opening_retained_earnings', '期初未分配利润'), ('accounts_receivable', '应收款'), ('customer_prepayments', '客户预收款'), ('inventory', '库存'), ('', '资金账户'), ('sales_revenue', '销售收入'), ('customer_transport_revenue', '客户人肉费收入'), ('cost_of_goods_sold', '销售成本'), ('transport_expense', '人肉费用'), ('purchase_in_transit', '在途采购'), ('salary_expense', '工资费用'), ('rent_expense', '房租费用'), ('utilities_expense', '水电费用'), ('other_expense', '其他经营费用'), ('dividend_distribution', '分红分配'), ('inventory_adjustment_gain', '库存调整收益'), ('inventory_adjustment_loss', '库存调整损失'), ('reconciliation_gain', '对账收益'), ('reconciliation_loss', '对账损失')], max_length=48, verbose_name='内部分类'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('opening_balance', '期初余额'), ('day1_opening', 'Day 1 期初资产'), ('exchange', '换汇'), ('transfer', '同币种转账'), ('sales_shipment', '销售出库'), ('sales_receipt', '销售收款'), ('sales_transport_cost', '销售人肉费'), ('sales_refund', '销售退款'), ('purchase_payment', '采购付款'), ('purchase_receipt', '采购到货'), ('expense', '经营费用'), ('dividend', '分红')], max_length=32, verbose_name='交易类型'),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('posted', '已入账')], default='draft', max_length=12)),
                ('total_cny', models.DecimalField(decimal_places=2, max_digits=22)),
                ('partner_a_amount_cny', models.DecimalField(decimal_places=2, max_digits=22)),
                ('partner_b_amount_cny', models.DecimalField(decimal_places=2, max_digits=22)),
                ('business_date', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('confirm_idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('confirm_request_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('warning_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('warning_ack', models.BooleanField(blank=True, null=True)),
                ('warning_code', models.CharField(blank=True, default='', max_length=64)),
                ('warning_retained_earnings_cny', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.ledgertransaction')),
                ('partner_a_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.fundaccount')),
                ('partner_b_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.fundaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),

        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('posted', '已入账')], default='posted', max_length=12)),
                ('category', models.CharField(choices=[('salary', '工资'), ('rent', '房租'), ('utilities', '水电'), ('other', '其他')], max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=8, max_digits=22)),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=22)),
                ('business_date', models.DateField()),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('note', models.TextField(blank=True, default='')),
                ('fund_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.fundaccount')),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounting.ledgertransaction')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),

        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('posted', '已入账')], default='posted', max_length=12)),
                ('rub_amount', models.DecimalField(decimal_places=2, max_digits=22)),
                ('cny_cost', models.DecimalField(decimal_places=2, max_digits=22)),
                ('business_date', models.DateField()),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('fund_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.fundaccount')),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounting.ledgertransaction')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cigars.purchaseorder')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='dividend',
            constraint=models.CheckConstraint(condition=models.Q(('partner_a_amount_cny__gte', 0), ('partner_b_amount_cny__gte', 0), ('total_cny__gte', 0)), name='dividend_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cny__gte', 0), ('original_amount__gte', 0)), name='expense_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchasepayment',
            constraint=models.CheckConstraint(condition=models.Q(('cny_cost__gte', 0), ('rub_amount__gte', 0)), name='purchase_payment_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'posted')), name='expense_status_posted'),
        ),
        migrations.AddConstraint(
            model_name='purchasepayment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'posted')), name='purchase_payment_status_posted'),
        ),
    ]
