# Generated by Django 6.0.6 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_accounting_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendDraftAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', '创建'), ('update', '编辑')], max_length=12)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('result_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dividend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.dividend')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDraftAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', '创建'), ('update', '编辑'), ('cancel', '取消')], max_length=12)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('result_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cigars.purchaseorder')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
    ]
