# Generated by Django 6.0.6 on 2026-08-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_expense_professional_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('personnel_salary', '人员费用 · 工资'), ('personnel_bonus', '人员费用 · 奖金 / 补贴'), ('personnel_benefits', '人员费用 · 员工福利'), ('personnel_recruiting', '人员费用 · 招聘 / 培训'), ('rent', '房租与物业 · 房租'), ('property', '房租与物业 · 物业管理费'), ('venue_service', '房租与物业 · 场地服务费'), ('electricity', '水电与能源 · 电费'), ('water', '水电与能源 · 水费'), ('gas_heating', '水电与能源 · 燃气 / 供暖'), ('other_energy', '水电与能源 · 其他能源'), ('transport_taxi', '交通 / 物流 · 打车'), ('transport_public', '交通 / 物流 · 公共交通'), ('transport_travel', '交通 / 物流 · 火车 / 飞机'), ('transport_delivery', '交通 / 物流 · 快递 / 配送'), ('transport_parking', '交通 / 物流 · 停车费 / 过路费'), ('transport_fuel', '交通 / 物流 · 燃油'), ('office_supplies', '办公 / 通讯 · 办公用品'), ('office_printing', '办公 / 通讯 · 打印 / 复印'), ('office_phone', '办公 / 通讯 · 电话费'), ('office_internet', '办公 / 通讯 · 网络费'), ('office_software', '办公 / 通讯 · 软件 / 订阅'), ('office_postage', '办公 / 通讯 · 邮寄费'), ('facility_equipment', '场地 / 设备 · 设备购买'), ('facility_tools', '场地 / 设备 · 小型工具'), ('facility_repair', '场地 / 设备 · 维修 / 保养'), ('facility_cleaning', '场地 / 设备 · 清洁'), ('marketing_advertising', '销售与营销 · 广告费'), ('marketing_platform', '销售与营销 · 平台服务费'), ('marketing_creative', '销售与营销 · 拍摄 / 设计'), ('marketing_gift', '销售与营销 · 客户礼品'), ('marketing_promotion', '销售与营销 · 促销活动'), ('professional_accounting', '专业服务 · 会计服务'), ('professional_legal', '专业服务 · 法律服务'), ('professional_consulting', '专业服务 · 咨询服务'), ('professional_design', '专业服务 · 设计服务'), ('professional_translation', '专业服务 · 翻译服务'), ('financial_interest', '财务费用 · 借款利息'), ('financial_bank_fee', '财务费用 · 银行手续费'), ('financial_payment_fee', '财务费用 · 支付手续费'), ('financial_account_fee', '财务费用 · 账户管理费'), ('tax', '税费与政府费用 · 税费'), ('registration', '税费与政府费用 · 注册费'), ('license', '税费与政府费用 · 许可证费'), ('notary', '税费与政府费用 · 公证 / 认证费'), ('other', '其他经营费用 · 其他')], default='', max_length=32),
        ),
    ]
