# Generated by Django 6.0.6 on 2026-09-14 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_expense_category_alter_expense_subcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerposting',
            name='category',
            field=models.CharField(blank=True, choices=[('opening_capital', '期初投入资本'), ('opening_retained_earnings', '期初未分配利润'), ('accounts_receivable', '应收款'), ('customer_prepayments', '客户预收款'), ('inventory', '库存'), ('', '资金账户'), ('sales_revenue', '销售收入'), ('customer_transport_revenue', '客户人肉费收入'), ('cost_of_goods_sold', '销售成本'), ('transport_expense', '人肉费用'), ('transport_settlement_expense', '运输结算费用'), ('purchase_in_transit', '在途采购'), ('salary_expense', '工资费用'), ('rent_expense', '房租费用'), ('utilities_expense', '水电费用'), ('professional_expense', '会计（专业服务）'), ('interest_expense', '利息支出（财务费用）'), ('other_expense', '其他经营费用'), ('dividend_distribution', '分红分配'), ('dividend_payable', '待付分红'), ('inventory_adjustment_gain', '库存调整收益'), ('inventory_adjustment_loss', '库存调整损失'), ('reconciliation_gain', '对账收益'), ('reconciliation_loss', '对账损失')], max_length=48, verbose_name='内部分类'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('opening_balance', '期初余额'), ('day1_opening', 'Day 1 期初资产'), ('exchange', '换汇'), ('transfer', '同币种转账'), ('sales_shipment', '销售出库'), ('sales_receipt', '销售收款'), ('sales_transport_cost', '销售人肉费'), ('sales_refund', '销售退款'), ('purchase_payment', '采购付款'), ('purchase_receipt', '采购到货'), ('expense', '经营费用'), ('dividend', '分红'), ('dividend_payout', '分红领取'), ('inventory_adjustment', '库存调整')], max_length=32, verbose_name='交易类型'),
        ),
        migrations.CreateModel(
            name='DividendRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(default='posted', editable=False, max_length=12)),
                ('total_cny', models.DecimalField(decimal_places=2, max_digits=22)),
                ('partner_a_name', models.CharField(max_length=255)),
                ('partner_b_name', models.CharField(max_length=255)),
                ('business_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('agent_source', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('warning_fingerprint', models.CharField(max_length=64)),
                ('warning_ack', models.BooleanField()),
                ('warning_retained_earnings_cny', models.DecimalField(decimal_places=2, max_digits=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounting.ledgertransaction')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DividendPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(default='posted', editable=False, max_length=12)),
                ('recipient_name', models.CharField(max_length=255)),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=22)),
                ('business_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('agent_source', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.fundaccount')),
                ('ledger_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounting.ledgertransaction')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='accounting.dividendround')),
            ],
            options={
                'ordering': ['business_date', 'id'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='dividendround',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'posted')), name='dividend_round_posted'),
        ),
        migrations.AddConstraint(
            model_name='dividendround',
            constraint=models.CheckConstraint(condition=models.Q(('total_cny__gt', 0)), name='dividend_round_positive'),
        ),
        migrations.AddConstraint(
            model_name='dividendround',
            constraint=models.CheckConstraint(condition=models.Q(('partner_a', models.F('partner_b')), _negated=True), name='dividend_round_different_partners'),
        ),
        migrations.AddConstraint(
            model_name='dividendpayout',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'posted')), name='dividend_payout_posted'),
        ),
        migrations.AddConstraint(
            model_name='dividendpayout',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cny__gt', 0)), name='dividend_payout_positive'),
        ),
    ]
